CREATE OR REPLACE TRIGGER "ZJJK".TRG_ZJJK_XNXG_CFK
  after insert or update or delete on ZJJK_XNXG_CFK
  for each row
declare
  -- local variables here
  v_count number:=0;
  v_sqlerrm varchar(4000);
  --v_yhm VARCHAR2(20):='';
begin
  --select YHM into v_yhm from middleof_ZJJK_XNXG_CFK  where VC_CFKID=:NEW.VC_CFKID;
  if inserting then
        select COUNT(0) into v_count from middleof_ZJJK_XNXG_CFK  where VC_CFKID=:NEW.VC_CFKID;
        if v_count >0 then
            UPDATE middleof_ZJJK_XNXG_CFK set
            VC_BGKID=:NEW.VC_BGKID  ,DT_CFRQ=:NEW.DT_CFRQ  ,VC_CFYS=:NEW.VC_CFYS  ,VC_HJHS=:NEW.VC_HJHS  ,VC_HJWHSYY=:NEW.VC_HJWHSYY  ,VC_JZDHS=:NEW.VC_JZDHS  ,VC_JZDHSYY=:NEW.VC_JZDHSYY  ,VC_HJQC=:NEW.VC_HJQC  ,VC_QYDZ=:NEW.VC_QYDZ  ,DT_QYRQ=:NEW.DT_QYRQ  ,DT_ZZRQ=:NEW.DT_ZZRQ  ,DT_JZRQ=:NEW.DT_JZRQ  ,DT_FBRQ=:NEW.DT_FBRQ  ,VC_SFHYZ=:NEW.VC_SFHYZ  ,DT_CXGLRQ=:NEW.DT_CXGLRQ  ,VC_CXYY=:NEW.VC_CXYY  ,VC_CXYYZM=:NEW.VC_CXYYZM  ,VC_SFFBSW=:NEW.VC_SFFBSW  ,DT_SWRQ=:NEW.DT_SWRQ  ,VC_SWYY=:NEW.VC_SWYY  ,VC_SWDD=:NEW.VC_SWDD  ,NB_SCQN=:NEW.NB_SCQN  ,NB_SCQY=:NEW.NB_SCQY  ,VC_SCBZ=:NEW.VC_SCBZ  ,VC_CJYH=:NEW.VC_CJYH  ,DT_CJSJ=:NEW.DT_CJSJ	,DT_XGSJ=:NEW.DT_XGSJ	,VC_XGYH=:NEW.VC_XGYH	,VC_QCD=:NEW.VC_QCD	,VC_QCSDM=:NEW.VC_QCSDM	,VC_QCQXDM=:NEW.VC_QCQXDM	,VC_QCJDDM=:NEW.VC_QCJDDM	,VC_QCJW=:NEW.VC_QCJW	,VC_QCXXDZ=:NEW.VC_QCXXDZ	,VC_SWICD=:NEW.VC_SWICD	,VC_SWICDMC=:NEW.VC_SWICDMC	,VC_ZLQK=:NEW.VC_ZLQK	,VC_JZS=:NEW.VC_JZS	,VC_GX=:NEW.VC_GX	,VC_SFDYYJZ=:NEW.VC_SFDYYJZ	,DT_QZRQ=:NEW.DT_QZRQ	,VC_XYS=:NEW.VC_XYS	,VC_JYYF=:NEW.VC_JYYF	,VC_FZQRKPF=:NEW.VC_FZQRKPF	,VC_CFRKPF=:NEW.VC_CFRKPF	,VC_YWZL=:NEW.VC_YWZL	,VC_YWZLQT=:NEW.VC_YWZLQT	,VC_GXBZ=:NEW.VC_GXBZ	,VC_ID=:NEW.VC_ID
            where VC_CFKID=:NEW.VC_CFKID;
         ELSE
             insert into middleof_ZJJK_XNXG_CFK
             (VC_CFKID	,VC_BGKID	,DT_CFRQ	,VC_CFYS	,VC_HJHS	,VC_HJWHSYY	,VC_JZDHS	,VC_JZDHSYY	,VC_HJQC	,VC_QYDZ	,DT_QYRQ	,DT_ZZRQ	,DT_JZRQ	,DT_FBRQ	,VC_SFHYZ	,DT_CXGLRQ	,VC_CXYY	,VC_CXYYZM	,VC_SFFBSW	,DT_SWRQ	,VC_SWYY	,VC_SWDD	,NB_SCQN	,NB_SCQY	,VC_SCBZ	,VC_CJYH	,DT_CJSJ	,DT_XGSJ	,VC_XGYH	,VC_QCD	,VC_QCSDM	,VC_QCQXDM	,VC_QCJDDM	,VC_QCJW	,VC_QCXXDZ	,VC_SWICD	,VC_SWICDMC	,VC_ZLQK	,VC_JZS	,VC_GX	,VC_SFDYYJZ	,DT_QZRQ	,VC_XYS	,VC_JYYF	,VC_FZQRKPF	,VC_CFRKPF	,VC_YWZL	,VC_YWZLQT	,VC_GXBZ	,VC_ID,OPERATE)
             values(:NEW.VC_CFKID	,:NEW.VC_BGKID	,:NEW.DT_CFRQ	,:NEW.VC_CFYS	,:NEW.VC_HJHS	,:NEW.VC_HJWHSYY	,:NEW.VC_JZDHS	,:NEW.VC_JZDHSYY	,:NEW.VC_HJQC	,:NEW.VC_QYDZ	,:NEW.DT_QYRQ	,:NEW.DT_ZZRQ	,:NEW.DT_JZRQ	,:NEW.DT_FBRQ	,:NEW.VC_SFHYZ	,:NEW.DT_CXGLRQ	,:NEW.VC_CXYY	,:NEW.VC_CXYYZM	,:NEW.VC_SFFBSW	,:NEW.DT_SWRQ	,:NEW.VC_SWYY	,:NEW.VC_SWDD	,:NEW.NB_SCQN	,:NEW.NB_SCQY	,:NEW.VC_SCBZ	,:NEW.VC_CJYH	,:NEW.DT_CJSJ	,:NEW.DT_XGSJ	,:NEW.VC_XGYH	,:NEW.VC_QCD	,:NEW.VC_QCSDM	,:NEW.VC_QCQXDM	,:NEW.VC_QCJDDM	,:NEW.VC_QCJW	,:NEW.VC_QCXXDZ	,:NEW.VC_SWICD	,:NEW.VC_SWICDMC	,:NEW.VC_ZLQK	,:NEW.VC_JZS	,:NEW.VC_GX	,:NEW.VC_SFDYYJZ	,:NEW.DT_QZRQ	,:NEW.VC_XYS	,:NEW.VC_JYYF	,:NEW.VC_FZQRKPF	,:NEW.VC_CFRKPF	,:NEW.VC_YWZL	,:NEW.VC_YWZLQT	,:NEW.VC_GXBZ	,:NEW.VC_ID,'insert');
   end if;
   elsif updating then
         select COUNT(0) into v_count from middleof_ZJJK_XNXG_CFK  where VC_CFKID=:NEW.VC_CFKID;
         if v_count >0 then
            UPDATE middleof_ZJJK_XNXG_CFK set
            VC_BGKID=:NEW.VC_BGKID	,DT_CFRQ=:NEW.DT_CFRQ	,VC_CFYS=:NEW.VC_CFYS	,VC_HJHS=:NEW.VC_HJHS	,VC_HJWHSYY=:NEW.VC_HJWHSYY	,VC_JZDHS=:NEW.VC_JZDHS	,VC_JZDHSYY=:NEW.VC_JZDHSYY	,VC_HJQC=:NEW.VC_HJQC	,VC_QYDZ=:NEW.VC_QYDZ	,DT_QYRQ=:NEW.DT_QYRQ	,DT_ZZRQ=:NEW.DT_ZZRQ	,DT_JZRQ=:NEW.DT_JZRQ	,DT_FBRQ=:NEW.DT_FBRQ	,VC_SFHYZ=:NEW.VC_SFHYZ	,DT_CXGLRQ=:NEW.DT_CXGLRQ	,VC_CXYY=:NEW.VC_CXYY	,VC_CXYYZM=:NEW.VC_CXYYZM	,VC_SFFBSW=:NEW.VC_SFFBSW	,DT_SWRQ=:NEW.DT_SWRQ	,VC_SWYY=:NEW.VC_SWYY	,VC_SWDD=:NEW.VC_SWDD	,NB_SCQN=:NEW.NB_SCQN	,NB_SCQY=:NEW.NB_SCQY	,VC_SCBZ=:NEW.VC_SCBZ	,VC_CJYH=:NEW.VC_CJYH	,DT_CJSJ=:NEW.DT_CJSJ	,DT_XGSJ=:NEW.DT_XGSJ	,VC_XGYH=:NEW.VC_XGYH	,VC_QCD=:NEW.VC_QCD	,VC_QCSDM=:NEW.VC_QCSDM	,VC_QCQXDM=:NEW.VC_QCQXDM	,VC_QCJDDM=:NEW.VC_QCJDDM	,VC_QCJW=:NEW.VC_QCJW	,VC_QCXXDZ=:NEW.VC_QCXXDZ	,VC_SWICD=:NEW.VC_SWICD	,VC_SWICDMC=:NEW.VC_SWICDMC	,VC_ZLQK=:NEW.VC_ZLQK	,VC_JZS=:NEW.VC_JZS	,VC_GX=:NEW.VC_GX	,VC_SFDYYJZ=:NEW.VC_SFDYYJZ	,DT_QZRQ=:NEW.DT_QZRQ	,VC_XYS=:NEW.VC_XYS	,VC_JYYF=:NEW.VC_JYYF	,VC_FZQRKPF=:NEW.VC_FZQRKPF	,VC_CFRKPF=:NEW.VC_CFRKPF	,VC_YWZL=:NEW.VC_YWZL	,VC_YWZLQT=:NEW.VC_YWZLQT	,VC_GXBZ=:NEW.VC_GXBZ	,VC_ID=:NEW.VC_ID
            where VC_CFKID=:NEW.VC_CFKID;
          ELSE
           insert into middleof_ZJJK_XNXG_CFK
             (VC_CFKID	,VC_BGKID	,DT_CFRQ	,VC_CFYS	,VC_HJHS	,VC_HJWHSYY	,VC_JZDHS	,VC_JZDHSYY	,VC_HJQC	,VC_QYDZ	,DT_QYRQ	,DT_ZZRQ	,DT_JZRQ	,DT_FBRQ	,VC_SFHYZ	,DT_CXGLRQ	,VC_CXYY	,VC_CXYYZM	,VC_SFFBSW	,DT_SWRQ	,VC_SWYY	,VC_SWDD	,NB_SCQN	,NB_SCQY	,VC_SCBZ	,VC_CJYH	,DT_CJSJ	,DT_XGSJ	,VC_XGYH	,VC_QCD	,VC_QCSDM	,VC_QCQXDM	,VC_QCJDDM	,VC_QCJW	,VC_QCXXDZ	,VC_SWICD	,VC_SWICDMC	,VC_ZLQK	,VC_JZS	,VC_GX	,VC_SFDYYJZ	,DT_QZRQ	,VC_XYS	,VC_JYYF	,VC_FZQRKPF	,VC_CFRKPF	,VC_YWZL	,VC_YWZLQT	,VC_GXBZ	,VC_ID,OPERATE)
             values(:NEW.VC_CFKID	,:NEW.VC_BGKID	,:NEW.DT_CFRQ	,:NEW.VC_CFYS	,:NEW.VC_HJHS	,:NEW.VC_HJWHSYY	,:NEW.VC_JZDHS	,:NEW.VC_JZDHSYY	,:NEW.VC_HJQC	,:NEW.VC_QYDZ	,:NEW.DT_QYRQ	,:NEW.DT_ZZRQ	,:NEW.DT_JZRQ	,:NEW.DT_FBRQ	,:NEW.VC_SFHYZ	,:NEW.DT_CXGLRQ	,:NEW.VC_CXYY	,:NEW.VC_CXYYZM	,:NEW.VC_SFFBSW	,:NEW.DT_SWRQ	,:NEW.VC_SWYY	,:NEW.VC_SWDD	,:NEW.NB_SCQN	,:NEW.NB_SCQY	,:NEW.VC_SCBZ	,:NEW.VC_CJYH	,:NEW.DT_CJSJ	,:NEW.DT_XGSJ	,:NEW.VC_XGYH	,:NEW.VC_QCD	,:NEW.VC_QCSDM	,:NEW.VC_QCQXDM	,:NEW.VC_QCJDDM	,:NEW.VC_QCJW	,:NEW.VC_QCXXDZ	,:NEW.VC_SWICD	,:NEW.VC_SWICDMC	,:NEW.VC_ZLQK	,:NEW.VC_JZS	,:NEW.VC_GX	,:NEW.VC_SFDYYJZ	,:NEW.DT_QZRQ	,:NEW.VC_XYS	,:NEW.VC_JYYF	,:NEW.VC_FZQRKPF	,:NEW.VC_CFRKPF	,:NEW.VC_YWZL	,:NEW.VC_YWZLQT	,:NEW.VC_GXBZ	,:NEW.VC_ID,'update');

    end if;
   elsif deleting then
         select COUNT(0) into v_count from middleof_ZJJK_XNXG_CFK  where VC_CFKID=:OLD.VC_CFKID;
         if v_count >0 then
            --DELETE middleof_ZJJK_XNXG_CFK where VC_CFKID=:NEW.VC_CFKID;  可能会出现修改状态，仍需要作删除处理
            UPDATE middleof_ZJJK_XNXG_CFK set OPERATE='delete' where VC_CFKID=:OLD.VC_CFKID;
          ELSE
             insert into middleof_ZJJK_XNXG_CFK (VC_CFKID,DT_CJSJ,VC_SCBZ,OPERATE)
             values(:OLD.VC_CFKID,:OLD.DT_CJSJ,:OLD.VC_SCBZ,'delete');
          end if;
   end if;
    --异常处理
   Exception
   WHEN OTHERS Then
    v_sqlerrm := (Sqlerrm || chr(10) || dbms_utility.format_error_backtrace);
    Insert Into BGK_ERRLOG
    Values
      ('心脑血管初访卡',
       'ZJJK_XNXG_CFK',
       'cjyh:' || :NEW.VC_CJYH,
       v_sqlerrm,
       sysdate,
       :NEW.VC_CFKID,
       'cs');

end TRG_ZJJK_XNXG_CFK;
