CREATE OR REPLACE TRIGGER "ZJJK".TRG_ZJJK_ZL_CCSFK
  after insert or update or delete on zjjk_zl_ccsfk
  for each row
declare
  -- local variables here
  v_count number:=0;
  v_sqlerrm varchar(4000);
  --v_yhm VARCHAR2(20):='';
begin
  --select YHM into v_yhm from middleof_zjjk_zl_ccsfk  where VC_SFKID=:NEW.VC_SFKID;
  if inserting then
        select COUNT(0) into v_count from middleof_zjjk_zl_ccsfk  where VC_SFKID=:NEW.VC_SFKID;
        if v_count >0 then
            UPDATE middleof_zjjk_zl_ccsfk set
            VC_BGKID=:NEW.VC_BGKID  ,VC_HZID=:NEW.VC_HZID  ,DT_SFRQ=:NEW.DT_SFRQ  ,NB_ZGJG=:NEW.NB_ZGJG  ,NB_ZGJG_QCDZ=:NEW.NB_ZGJG_QCDZ  ,NB_ZGJG_SFYY=:NEW.NB_ZGJG_SFYY  ,DT_SWRQ=:NEW.DT_SWRQ  ,VC_SWYY=:NEW.VC_SWYY  ,VC_SWDD=:NEW.VC_SWDD  ,VC_SCQ=:NEW.VC_SCQ  ,VC_ZLXM=:NEW.VC_ZLXM  ,VC_SSYY=:NEW.VC_SSYY  ,VC_HLYY=:NEW.VC_HLYY  ,VC_FLYY=:NEW.VC_FLYY  ,VC_SFZY=:NEW.VC_SFZY  ,DT_ZYSJ=:NEW.DT_ZYSJ  ,VC_CZLQK=:NEW.VC_CZLQK  ,VC_MQQK=:NEW.VC_MQQK  ,NB_KSPF=:NEW.NB_KSPF  ,VC_YSQM=:NEW.VC_YSQM  ,VC_HZQM=:NEW.VC_HZQM  ,VC_SCBZ=:NEW.VC_SCBZ  ,VC_CJYH=:NEW.VC_CJYH  ,DT_CJSJ=:NEW.DT_CJSJ  ,DT_XGSJ=:NEW.DT_XGSJ  ,VC_XGYH=:NEW.VC_XGYH  ,VC_SFCF=:NEW.VC_SFCF  ,VC_SCZZRQ=:NEW.VC_SCZZRQ  ,VC_SCJZSJ=:NEW.VC_SCJZSJ  ,VC_SCSSYY=:NEW.VC_SCSSYY  ,VC_SCSSRQ=:NEW.VC_SCSSRQ  ,VC_SCSSXZ=:NEW.VC_SCSSXZ  ,VC_ZYH=:NEW.VC_ZYH  ,VC_BLH=:NEW.VC_BLH  ,VC_QCD=:NEW.VC_QCD  ,VC_QCSDM=:NEW.VC_QCSDM  ,VC_QCQXDM=:NEW.VC_QCQXDM  ,VC_QCJDDM=:NEW.VC_QCJDDM  ,VC_QCJW=:NEW.VC_QCJW  ,VC_SFQC=:NEW.VC_SFQC  ,DT_QCSJ=:NEW.DT_QCSJ  ,VC_QCXXDZ=:NEW.VC_QCXXDZ  ,VC_HJHS=:NEW.VC_HJHS  ,VC_ZYBW=:NEW.VC_ZYBW  ,VC_ZLJZS=:NEW.VC_ZLJZS  ,VC_GX=:NEW.VC_GX  ,VC_LB=:NEW.VC_LB  ,VC_CXGLRQ=:NEW.VC_CXGLRQ  ,VC_CXGLYY=:NEW.VC_CXGLYY  ,VC_JZDHS=:NEW.VC_JZDHS  ,VC_WHSYY=:NEW.VC_WHSYY  ,VC_SSYY1=:NEW.VC_SSYY1	,VC_SSYY2=:NEW.VC_SSYY2	,VC_HLYY1=:NEW.VC_HLYY1	,VC_HLYY2=:NEW.VC_HLYY2	,VC_FLYY1=:NEW.VC_FLYY1	,VC_FLYY2=:NEW.VC_FLYY2	,VC_HJWHSYY=:NEW.VC_HJWHSYY	,VC_SWICD=:NEW.VC_SWICD	,VC_SWICDMC=:NEW.VC_SWICDMC	,VC_XYS=:NEW.VC_XYS	,VC_RJXYZS=:NEW.VC_RJXYZS	,VC_SCXYRQN=:NEW.VC_SCXYRQN	,VC_SCXYRQY=:NEW.VC_SCXYRQY	,VC_MCXYRQN=:NEW.VC_MCXYRQN	,VC_MCXYRQY=:NEW.VC_MCXYRQY	,VC_HJXYSJN=:NEW.VC_HJXYSJN	,VC_HJXYSJY=:NEW.VC_HJXYSJY	,NB_TZ=:NEW.NB_TZ	,NB_SG=:NEW.NB_SG	,VC_GXBZ=:NEW.VC_GXBZ	,VC_ID=:NEW.VC_ID	,VC_JZDHSYY=:NEW.VC_JZDHSYY
            where VC_SFKID=:NEW.VC_SFKID;
         ELSE
             insert into middleof_zjjk_zl_ccsfk
             (VC_SFKID	,VC_BGKID	,VC_HZID	,DT_SFRQ	,NB_ZGJG	,NB_ZGJG_QCDZ	,NB_ZGJG_SFYY	,DT_SWRQ	,VC_SWYY	,VC_SWDD	,VC_SCQ	,VC_ZLXM	,VC_SSYY	,VC_HLYY	,VC_FLYY	,VC_SFZY	,DT_ZYSJ	,VC_CZLQK	,VC_MQQK	,NB_KSPF	,VC_YSQM	,VC_HZQM	,VC_SCBZ	,VC_CJYH	,DT_CJSJ	,DT_XGSJ	,VC_XGYH	,VC_SFCF	,VC_SCZZRQ	,VC_SCJZSJ	,VC_SCSSYY	,VC_SCSSRQ	,VC_SCSSXZ	,VC_ZYH	,VC_BLH	,VC_QCD	,VC_QCSDM	,VC_QCQXDM	,VC_QCJDDM	,VC_QCJW	,VC_SFQC	,DT_QCSJ	,VC_QCXXDZ	,VC_HJHS	,VC_ZYBW	,VC_ZLJZS	,VC_GX	,VC_LB	,VC_CXGLRQ	,VC_CXGLYY	,VC_JZDHS	,VC_WHSYY	,VC_SSYY1	,VC_SSYY2	,VC_HLYY1	,VC_HLYY2	,VC_FLYY1	,VC_FLYY2	,VC_HJWHSYY	,VC_SWICD	,VC_SWICDMC	,VC_XYS	,VC_RJXYZS	,VC_SCXYRQN	,VC_SCXYRQY	,VC_MCXYRQN	,VC_MCXYRQY	,VC_HJXYSJN	,VC_HJXYSJY	,NB_TZ	,NB_SG	,VC_GXBZ	,VC_ID	,VC_JZDHSYY,OPERATE)
             values(:NEW.VC_SFKID	,:NEW.VC_BGKID	,:NEW.VC_HZID	,:NEW.DT_SFRQ	,:NEW.NB_ZGJG	,:NEW.NB_ZGJG_QCDZ	,:NEW.NB_ZGJG_SFYY	,:NEW.DT_SWRQ	,:NEW.VC_SWYY	,:NEW.VC_SWDD	,:NEW.VC_SCQ	,:NEW.VC_ZLXM	,:NEW.VC_SSYY	,:NEW.VC_HLYY	,:NEW.VC_FLYY	,:NEW.VC_SFZY	,:NEW.DT_ZYSJ	,:NEW.VC_CZLQK	,:NEW.VC_MQQK	,:NEW.NB_KSPF	,:NEW.VC_YSQM	,:NEW.VC_HZQM	,:NEW.VC_SCBZ	,:NEW.VC_CJYH	,:NEW.DT_CJSJ	,:NEW.DT_XGSJ	,:NEW.VC_XGYH	,:NEW.VC_SFCF	,:NEW.VC_SCZZRQ	,:NEW.VC_SCJZSJ	,:NEW.VC_SCSSYY	,:NEW.VC_SCSSRQ	,:NEW.VC_SCSSXZ	,:NEW.VC_ZYH	,:NEW.VC_BLH	,:NEW.VC_QCD	,:NEW.VC_QCSDM	,:NEW.VC_QCQXDM	,:NEW.VC_QCJDDM	,:NEW.VC_QCJW	,:NEW.VC_SFQC	,:NEW.DT_QCSJ	,:NEW.VC_QCXXDZ	,:NEW.VC_HJHS	,:NEW.VC_ZYBW	,:NEW.VC_ZLJZS	,:NEW.VC_GX	,:NEW.VC_LB	,:NEW.VC_CXGLRQ	,:NEW.VC_CXGLYY	,:NEW.VC_JZDHS	,:NEW.VC_WHSYY	,:NEW.VC_SSYY1	,:NEW.VC_SSYY2	,:NEW.VC_HLYY1	,:NEW.VC_HLYY2	,:NEW.VC_FLYY1	,:NEW.VC_FLYY2	,:NEW.VC_HJWHSYY	,:NEW.VC_SWICD	,:NEW.VC_SWICDMC	,:NEW.VC_XYS	,:NEW.VC_RJXYZS	,:NEW.VC_SCXYRQN	,:NEW.VC_SCXYRQY	,:NEW.VC_MCXYRQN	,:NEW.VC_MCXYRQY	,:NEW.VC_HJXYSJN	,:NEW.VC_HJXYSJY	,:NEW.NB_TZ	,:NEW.NB_SG	,:NEW.VC_GXBZ	,:NEW.VC_ID	,:NEW.VC_JZDHSYY,'insert');
   end if;
   elsif updating then
         select COUNT(0) into v_count from middleof_zjjk_zl_ccsfk  where VC_SFKID=:NEW.VC_SFKID;
         if v_count >0 then
            UPDATE middleof_zjjk_zl_ccsfk set
            VC_BGKID=:NEW.VC_BGKID	,VC_HZID=:NEW.VC_HZID	,DT_SFRQ=:NEW.DT_SFRQ	,NB_ZGJG=:NEW.NB_ZGJG	,NB_ZGJG_QCDZ=:NEW.NB_ZGJG_QCDZ	,NB_ZGJG_SFYY=:NEW.NB_ZGJG_SFYY	,DT_SWRQ=:NEW.DT_SWRQ	,VC_SWYY=:NEW.VC_SWYY	,VC_SWDD=:NEW.VC_SWDD	,VC_SCQ=:NEW.VC_SCQ	,VC_ZLXM=:NEW.VC_ZLXM	,VC_SSYY=:NEW.VC_SSYY	,VC_HLYY=:NEW.VC_HLYY	,VC_FLYY=:NEW.VC_FLYY	,VC_SFZY=:NEW.VC_SFZY	,DT_ZYSJ=:NEW.DT_ZYSJ	,VC_CZLQK=:NEW.VC_CZLQK	,VC_MQQK=:NEW.VC_MQQK	,NB_KSPF=:NEW.NB_KSPF	,VC_YSQM=:NEW.VC_YSQM	,VC_HZQM=:NEW.VC_HZQM	,VC_SCBZ=:NEW.VC_SCBZ	,VC_CJYH=:NEW.VC_CJYH	,DT_CJSJ=:NEW.DT_CJSJ	,DT_XGSJ=:NEW.DT_XGSJ	,VC_XGYH=:NEW.VC_XGYH	,VC_SFCF=:NEW.VC_SFCF	,VC_SCZZRQ=:NEW.VC_SCZZRQ	,VC_SCJZSJ=:NEW.VC_SCJZSJ	,VC_SCSSYY=:NEW.VC_SCSSYY	,VC_SCSSRQ=:NEW.VC_SCSSRQ	,VC_SCSSXZ=:NEW.VC_SCSSXZ	,VC_ZYH=:NEW.VC_ZYH	,VC_BLH=:NEW.VC_BLH	,VC_QCD=:NEW.VC_QCD	,VC_QCSDM=:NEW.VC_QCSDM	,VC_QCQXDM=:NEW.VC_QCQXDM	,VC_QCJDDM=:NEW.VC_QCJDDM	,VC_QCJW=:NEW.VC_QCJW	,VC_SFQC=:NEW.VC_SFQC	,DT_QCSJ=:NEW.DT_QCSJ	,VC_QCXXDZ=:NEW.VC_QCXXDZ	,VC_HJHS=:NEW.VC_HJHS	,VC_ZYBW=:NEW.VC_ZYBW	,VC_ZLJZS=:NEW.VC_ZLJZS	,VC_GX=:NEW.VC_GX	,VC_LB=:NEW.VC_LB	,VC_CXGLRQ=:NEW.VC_CXGLRQ	,VC_CXGLYY=:NEW.VC_CXGLYY	,VC_JZDHS=:NEW.VC_JZDHS	,VC_WHSYY=:NEW.VC_WHSYY	,VC_SSYY1=:NEW.VC_SSYY1	,VC_SSYY2=:NEW.VC_SSYY2	,VC_HLYY1=:NEW.VC_HLYY1	,VC_HLYY2=:NEW.VC_HLYY2	,VC_FLYY1=:NEW.VC_FLYY1	,VC_FLYY2=:NEW.VC_FLYY2	,VC_HJWHSYY=:NEW.VC_HJWHSYY	,VC_SWICD=:NEW.VC_SWICD	,VC_SWICDMC=:NEW.VC_SWICDMC	,VC_XYS=:NEW.VC_XYS	,VC_RJXYZS=:NEW.VC_RJXYZS	,VC_SCXYRQN=:NEW.VC_SCXYRQN	,VC_SCXYRQY=:NEW.VC_SCXYRQY	,VC_MCXYRQN=:NEW.VC_MCXYRQN	,VC_MCXYRQY=:NEW.VC_MCXYRQY	,VC_HJXYSJN=:NEW.VC_HJXYSJN	,VC_HJXYSJY=:NEW.VC_HJXYSJY	,NB_TZ=:NEW.NB_TZ	,NB_SG=:NEW.NB_SG	,VC_GXBZ=:NEW.VC_GXBZ	,VC_ID=:NEW.VC_ID	,VC_JZDHSYY=:NEW.VC_JZDHSYY
            where VC_SFKID=:NEW.VC_SFKID;
          ELSE
             insert into middleof_zjjk_zl_ccsfk
             (VC_SFKID	,VC_BGKID	,VC_HZID	,DT_SFRQ	,NB_ZGJG	,NB_ZGJG_QCDZ	,NB_ZGJG_SFYY	,DT_SWRQ	,VC_SWYY	,VC_SWDD	,VC_SCQ	,VC_ZLXM	,VC_SSYY	,VC_HLYY	,VC_FLYY	,VC_SFZY	,DT_ZYSJ	,VC_CZLQK	,VC_MQQK	,NB_KSPF	,VC_YSQM	,VC_HZQM	,VC_SCBZ	,VC_CJYH	,DT_CJSJ	,DT_XGSJ	,VC_XGYH	,VC_SFCF	,VC_SCZZRQ	,VC_SCJZSJ	,VC_SCSSYY	,VC_SCSSRQ	,VC_SCSSXZ	,VC_ZYH	,VC_BLH	,VC_QCD	,VC_QCSDM	,VC_QCQXDM	,VC_QCJDDM	,VC_QCJW	,VC_SFQC	,DT_QCSJ	,VC_QCXXDZ	,VC_HJHS	,VC_ZYBW	,VC_ZLJZS	,VC_GX	,VC_LB	,VC_CXGLRQ	,VC_CXGLYY	,VC_JZDHS	,VC_WHSYY	,VC_SSYY1	,VC_SSYY2	,VC_HLYY1	,VC_HLYY2	,VC_FLYY1	,VC_FLYY2	,VC_HJWHSYY	,VC_SWICD	,VC_SWICDMC	,VC_XYS	,VC_RJXYZS	,VC_SCXYRQN	,VC_SCXYRQY	,VC_MCXYRQN	,VC_MCXYRQY	,VC_HJXYSJN	,VC_HJXYSJY	,NB_TZ	,NB_SG	,VC_GXBZ	,VC_ID	,VC_JZDHSYY,OPERATE)
             values(:NEW.VC_SFKID	,:NEW.VC_BGKID	,:NEW.VC_HZID	,:NEW.DT_SFRQ	,:NEW.NB_ZGJG	,:NEW.NB_ZGJG_QCDZ	,:NEW.NB_ZGJG_SFYY	,:NEW.DT_SWRQ	,:NEW.VC_SWYY	,:NEW.VC_SWDD	,:NEW.VC_SCQ	,:NEW.VC_ZLXM	,:NEW.VC_SSYY	,:NEW.VC_HLYY	,:NEW.VC_FLYY	,:NEW.VC_SFZY	,:NEW.DT_ZYSJ	,:NEW.VC_CZLQK	,:NEW.VC_MQQK	,:NEW.NB_KSPF	,:NEW.VC_YSQM	,:NEW.VC_HZQM	,:NEW.VC_SCBZ	,:NEW.VC_CJYH	,:NEW.DT_CJSJ	,:NEW.DT_XGSJ	,:NEW.VC_XGYH	,:NEW.VC_SFCF	,:NEW.VC_SCZZRQ	,:NEW.VC_SCJZSJ	,:NEW.VC_SCSSYY	,:NEW.VC_SCSSRQ	,:NEW.VC_SCSSXZ	,:NEW.VC_ZYH	,:NEW.VC_BLH	,:NEW.VC_QCD	,:NEW.VC_QCSDM	,:NEW.VC_QCQXDM	,:NEW.VC_QCJDDM	,:NEW.VC_QCJW	,:NEW.VC_SFQC	,:NEW.DT_QCSJ	,:NEW.VC_QCXXDZ	,:NEW.VC_HJHS	,:NEW.VC_ZYBW	,:NEW.VC_ZLJZS	,:NEW.VC_GX	,:NEW.VC_LB	,:NEW.VC_CXGLRQ	,:NEW.VC_CXGLYY	,:NEW.VC_JZDHS	,:NEW.VC_WHSYY	,:NEW.VC_SSYY1	,:NEW.VC_SSYY2	,:NEW.VC_HLYY1	,:NEW.VC_HLYY2	,:NEW.VC_FLYY1	,:NEW.VC_FLYY2	,:NEW.VC_HJWHSYY	,:NEW.VC_SWICD	,:NEW.VC_SWICDMC	,:NEW.VC_XYS	,:NEW.VC_RJXYZS	,:NEW.VC_SCXYRQN	,:NEW.VC_SCXYRQY	,:NEW.VC_MCXYRQN	,:NEW.VC_MCXYRQY	,:NEW.VC_HJXYSJN	,:NEW.VC_HJXYSJY	,:NEW.NB_TZ	,:NEW.NB_SG	,:NEW.VC_GXBZ	,:NEW.VC_ID	,:NEW.VC_JZDHSYY,'update');

    end if;
   elsif deleting then
         select COUNT(0) into v_count from middleof_zjjk_zl_ccsfk  where VC_SFKID=:OLD.VC_SFKID;
         if v_count >0 then
            --DELETE middleof_zjjk_zl_ccsfk where VC_SFKID=:NEW.VC_SFKID;  可能会出现修改状态，仍需要作删除处理
            UPDATE middleof_zjjk_zl_ccsfk set OPERATE='delete' where VC_SFKID=:OLD.VC_SFKID;
          ELSE
             insert into middleof_zjjk_zl_ccsfk (VC_SFKID,DT_CJSJ,VC_SCBZ,OPERATE)
             values(:OLD.VC_SFKID,:OLD.DT_CJSJ,:OLD.VC_SCBZ,'delete');
          end if;
   end if;
    --异常处理
   Exception
   WHEN OTHERS Then
    v_sqlerrm := (Sqlerrm || chr(10) || dbms_utility.format_error_backtrace);
    Insert Into BGK_ERRLOG
    Values
      ('肿瘤初次随访卡',
       'zjjk_zl_ccsfk',
       'cjyh:' || :NEW.VC_CJYH,
       v_sqlerrm,
       sysdate,
       :NEW.VC_SFKID,
       'cs');

end TRG_ZJJK_ZL_CCSFK;
