 select        a.vc_bgkid,
               a.vc_ccid,
               a.vc_ckbz,
               a.vc_xsrid,
               a.vc_jkdw,
               a.vc_jkys,
               a.dt_jksj,
               a.vc_qyid,
               a.vc_xsrxb,
               dts(a.dt_csrq,0) dt_csrq,
               a.vc_csyz,
               a.nb_cstz,
               a.nb_cssc,
               a.vc_csxxdz,
               a.vc_hkd,
               a.vc_hjhs,
               a.vc_whsyy,
               a.vc_jkzt,
               a.vc_mqxm,
               a.vc_mqnl,
               a.vc_mqgj,
               a.vc_mqmz,
               a.vc_mqsfzbh,
               a.vc_mqhkszd,
               a.vc_fqxm,
               a.vc_fqnl,
               a.vc_fqgj,
               a.vc_fqmz,
               a.vc_fqsfzbh,
               a.vc_fqhkszd,
               a.vc_jtjzdz,
               a.vc_csddfl,
               a.vc_xsrjhrjz,
               a.vc_jsrqz,
               a.vc_jsjgmc,
               a.vc_lxdh,
               a.vc_yzbm,
               a.vc_csyyjlbh,
               a.vc_mqblh,
               a.vc_scbz,
               a.vc_gldwdm,
               a.vc_czdwdm,
               a.vc_xsrsfch,
               dts(a.dt_swrq,0) dt_swrq,
               a.vc_swyy,
               a.dt_czsj,
               a.vc_czyh,
               a.dt_xgsj,
               a.vc_xgyh,
               a.vc_bgklb,
               a.vc_bz,
               a.vc_sdm,
               a.vc_qdm,
               a.vc_jddm,
               a.vc_shbz,
               a.vc_khid,
               a.vc_khzt,
               a.vc_shid,
               a.vc_cssdm,
               a.vc_csqxdm,
               a.vc_csjddm,
               a.vc_hkqc,
               a.vc_qcsdm,
               a.vc_qcqxdm,
               a.vc_qcjddm,
               dts(a.dt_qcsj,0) dt_qcsj,
               a.vc_qcxxdz,
               a.vc_cszh,
               a.vc_hkxxdz,
               a.vc_csjw,
               a.vc_hkjw,
               a.vc_fqgjqt,
               a.vc_mqgjqt,
               a.vc_csddflqt,
               a.vc_jsdw,
               dts(a.dt_qfrq,0) dt_qfrq,
               a.vc_qcjw,
               a.vc_csdd,
               a.vc_hkqcd,
               a.vc_jsdwszs,
               a.vc_jsdwszq,
               a.vc_bgkzt,
               a.vc_xxly,
               a.vc_shzt,
               a.vc_khbz,
               a.vc_sdqr,
               a.vc_khjg,
               a.vc_hkshfdm,
               a.vc_sfsw,
               a.vc_shwtgyy,
               a.vc_shwtgyy1,
               a.vc_jkdws,
               a.vc_jkdwqx,
               dts(a.dt_qxshsj,0) dt_qxshsj,
               dts(a.dt_yyshsj,0) dt_yyshsj,
               b.mc vc_jkdw_mc
        from  zjmb_cs_bgk a, p_yljg b
        where a.vc_bgkid=#{vc_bgkid}
          and a.vc_jkdw = b.dm(+)