select a.vc_bgkid,
       a.vc_ccid,
       a.vc_ckbz,
       a.vc_xm,
       a.vc_jkdw,
       a.nb_jkyybm,
       a.vc_jkys,
       dts(a.dt_jksj, 0) as dt_jksj,
       a.vc_xb,
       a.vc_mz,
       a.vc_zy,
       a.vc_hjdzlx,
       a.vc_hjdz,
       a.vc_hjdzbm,
       a.vc_hyzk,
       a.vc_whcd,
       dts(a.dt_swrq, 0) as dt_swrq,
       a.vc_sznl,
       a.vc_sfzhm,
       a.vc_rqfl,
       a.vc_swdd,
       a.vc_sqczdzlx,
       a.vc_sqxxdz,
       a.vc_sqzgzddw,
       a.vc_icdbm,
       a.vc_zdyj,
       a.vc_gbsy,
       a.nb_gbsybm,
       a.vc_qtjbzd,
       a.nb_qtjbzdicd,
       a.vc_jsxm,
       a.vc_jslxdh,
       a.vc_jsdz,
       a.vc_bgklb,
       a.vc_zyh,
       a.vc_scbz,
       a.vc_gldwdm,
       a.vc_cjdwdm,
       dts(a.dt_cjsj, 0) as dt_cjsj,
       a.vc_cjyh,
       dts(a.dt_xgsj, 0) as dt_xgsj,
       a.vc_xgyh,
       a.vc_azjswjb,
       a.nb_azjswjbicd,
       a.vc_afbdswsjjg,
       a.vc_afbdswsjdw,
       a.vc_bzjswjb,
       a.nb_bzjswjbidc,
       a.vc_bfbdswsjjg,
       a.vc_bfbdswsjdw,
       a.vc_czjswjb,
       a.nb_czjswjbicd,
       a.vc_cfbdswsjjg,
       a.vc_cfbdswsjdw,
       a.vc_dzjswjb,
       a.nb_dajswjbicd,
       a.vc_dfbdswsjjg,
       a.vc_dfbdswsjdw,
       a.vc_szsqbljzztz,
       a.vc_bdczxm,
       a.vc_yszgx,
       a.vc_lxdzhgzdw,
       a.vc_bdczdh,
       a.vc_sytd,
       a.vc_bdczqm,
       dts(a.dt_dcrq, 0) as dt_dcrq,
       dts(a.dt_scsj, 0) as dt_scsj,
       dts(a.dt_lrsj, 0) as dt_lrsj,
       a.vc_lrrid,
       a.vc_shbz,
       dts(a.dt_shsj, 0) as dt_shsj,
       a.vc_kpzt,
       a.vc_kply,
       a.vc_hksdm,
       a.vc_hkqxdm,
       a.vc_hkjddm,
       a.vc_cssdm,
       a.vc_csqxdm,
       a.vc_csjddm,
       dts(a.dt_csrq, 0) as dt_csrq,
       a.vc_wbswyy,
       a.vc_ebm,
       a.vc_ysqm,
       a.vc_hkhs,
       a.vc_whsyy,
       a.vc_hkqc,
       a.vc_qcsdm,
       a.vc_qcqxdm,
       a.vc_qcjddm,
       dts(a.dt_qcsj, 0) as dt_qcsj,
       a.vc_bz,
       a.vc_shid,
       a.vc_khzt,
       a.vc_khid,
       a.vc_khjg,
       a.vc_hkxxdz,
       a.vc_qcxxdz,
       a.vc_sqgzdw,
       a.vc_hkjw,
       a.vc_qcjw,
       a.fenleitj,
       a.vc_ezjswjb,
       a.nb_eajswjbicd,
       a.vc_efbdswsjjg,
       a.vc_efbdswsjdw,
       a.vc_fzjswjb,
       a.nb_fajswjbicd,
       a.vc_ffbdswsjjg,
       a.vc_ffbdswsjdw,
       a.vc_gzjswjb,
       a.nb_gajswjbicd,
       a.vc_gfbdswsjjg,
       a.vc_gfbdswsjdw,
       a.vc_hkqcs,
       dts(a.dt_tbrq, 0),
       a.vc_xxly,
       a.vc_qcsfdm,
       a.vc_qyid,
       a.vc_shzt,
       a.vc_khbz,
       a.vc_xnxgbfzt,
       a.vc_tnbbfzt,
       a.vc_zlbfzt,
       a.vc_sdqr,
       a.fenleitjmc,
       a.vc_azjswjb1,
       a.vc_bzjswjb1,
       a.vc_czjswjb1,
       a.vc_dzjswjb1,
       a.vc_ezjswjb1,
       a.vc_fzjswjb1,
       a.vc_gzjswjb1,
       a.vc_shwtgyy,
       a.vc_shwtgyy1,
       a.vc_dyqbh,
       dts(a.dt_yyshsj, 0) as dt_yyshsj,
       dts(a.dt_sfsj, 0) as dt_sfsj,
       dts(a.dt_qxzssj, 0) as dt_qxzssj,
       a.vc_zjlx,
       a.vc_rsqk,
       a.vc_wshksdm,
       a.vc_wshkqxdm,
       a.vc_wshkjddm,
       a.vc_wshkjw,
       a.vc_gjhdq,
       a.vc_wshkshendm,
       a.vc_jzqcs,
       a.vc_jzsdm,
       a.vc_jzqxdm,
       a.vc_jzjddm,
       a.vc_jzjw,
       a.vc_wsjzshendm,
       a.vc_wsjzsdm,
       a.vc_wsjzqxdm,
       a.vc_wsjzjddm,
       a.vc_wsjzjw,
       a.vc_gxbz,
       a.vc_id,
       a.is_pass,
       a.validate_detail,
       dts(a.validate_date, 0) as validate_date,
       a.vc_hzicd,
       a.uploadcountry,
       a.requestid,
       a.upload_areaeport,
       b.mc vc_jkdw_mc
  from zjmb_sw_bgk a, p_yljg b
 where a.vc_bgkid = #{vc_bgkid}
   and a.vc_jkdw = b.dm(+)