select a.vc_bgkid,
       a.vc_bgklx,
       a.vc_hzid,
       a.vc_icd10,
       a.vc_tnblx,
       a.vc_wxys,
       a.vc_wxystz,
       a.vc_wxyssg,
       a.vc_tnbs,
       a.vc_jzsrs,
       a.vc_ywbfz,
       a.vc_zslcbx,
       a.vc_zslcbxqt,
       a.nb_kfxtz,
       a.nb_sjxtz,
       a.nb_xjptt,
       a.nb_zdgc,
       a.nb_e4hdlc,
       a.nb_e5ldlc,
       a.nb_gysz,
       a.nb_nwldb,
       a.nbthxhdb,
       a.vc_bszyqt,
       a.vc_zddw,
       a.vc_bgdw,
       a.vc_bgys,
       a.dt_bgrq,
       a.vc_sfsw,
       a.dt_swrq,
       a.vc_swyy,
       a.vc_swicd10,
       a.vc_swicdmc,
       a.vc_bszy,
       a.vc_scbz,
       a.vc_ccid,
       a.vc_ckbz,
       a.vc_sfbb,
       a.vc_sdqrzt,
       a.dt_qrsj,
       a.vc_sdqrid,
       a.vc_cjdw,
       a.dt_xgsj,
       a.vc_xgdw,
       a.vc_gldw,
       a.vc_shbz,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_SHZT',a.vc_shbz) vc_shbz_text,
       a.vc_shwtgyy1,
       a.vc_shwtgyy2,
       a.vc_khbz,
       a.vc_khjg,
       a.vc_smtjid,
       a.vc_qybz,
       a.vc_hkhs,
       a.vc_hkwhsyy,
       a.vc_jzhs,
       a.vc_jzwhsyy,
       a.vc_cxgl,
       a.vc_qcbz,
       a.vc_xgyh,
       a.vc_cjyh,
       a.vc_xxly,
       a.vc_bz,
       a.dt_dcrq,
       a.vc_dcr,
       a.vc_zdyh,
       a.vc_swxx,
       a.vc_bgdwqx,
       a.vc_zgzddw,
       a.vc_sznl,
       a.vc_icdo,
       a.vc_zyh,
       a.vc_mzh,
       a.vc_bqygzbr,
       a.vc_xzqybm,
       a.vc_bgkzt,
       a.vc_bgkcode,
       a.vc_qcd,
       a.vc_qcsdm,
       a.vc_qcqxdm,
       a.vc_qcjddm,
       a.vc_qcjw,
       a.vc_sfqc,
       a.dt_qcsj,
       a.vc_qcxxdz,
       a.vc_shid,
       a.vc_khid,
       a.vc_khzt,
       a.vc_shzt,
       a.vc_cfzt,
       a.vc_shwtgyy,
       a.vc_bks,
       a.vc_bkq,
       a.vc_bmi,
       a.vc_wtzt,
       a.vc_ywtdw,
       a.vc_sqsl,
       a.vc_jjsl,
       a.vc_ywtjd,
       a.vc_ywtjw,
       a.vc_ywtxxdz,
       a.vc_ywtjgdm,
       a.vc_lszy,
       a.vc_state,
       a.dt_yyshsj,
       a.dt_qxshsj,
       a.vc_bksznl,
       a.dt_cfsj,
       a.dt_sfsj,
       a.dt_qxzssj,
       a.vc_id,
       b.vc_hzxm,
       b.vc_hzxb,
       b.vc_hzmz,
       b.vc_whcd,
       dts(b.dt_hzcsrq,0) dt_hzcsrq,
       b.vc_sfzh,
       b.vc_lxdh,
       b.vc_hydm,
       b.vc_zydm,
       b.vc_gzdw,
       b.vc_hkshen,
       b.vc_hks,
       b.vc_hkqx,
       b.vc_hkjd,
       b.vc_hkjw,
       b.vc_hkxxdz,
       b.vc_jzds,
       b.vc_jzs,
       b.vc_jzqx,
       b.vc_jzjd,
       b.vc_jzjw,
       b.vc_jzxxdz,
       c.vc_zkid,
       c.vc_fkid,
       dts(a.dt_sczdrq, 0) dt_sczdrq,
       dts(a.dt_swrq, 0) dt_swrq,
       dts(a.dt_cjsj, 0) dt_cjsj,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKZT',a.vc_bgkzt) vc_bgkzt_text,
       decode(nvl(a.vc_cfzt, '0'), '0', '未访', '1', '已访', vc_cfzt) vc_cfzt_text,
       decode(b.vc_hzxb, '1', '男', '2', '女') vc_hzxb_text,
       dts(a.dt_qxshsj, 0) dt_qxshsj,
       dts(b.dt_hzcsrq, 0) dt_hzcsrq,
       decode(c.vc_zkid, c.vc_fkid, '主卡', '副卡') zfkbz_text,
       decode(vc_hkshen,
              '0',
              '浙江省' ||
              pkg_zjmb_tnb.fun_getxzqhmc(vc_hks) ||
              pkg_zjmb_tnb.fun_getxzqhmc(vc_hkqx) ||
              pkg_zjmb_tnb.fun_getxzqhmc(vc_hkjd) ||
              vc_hkjw||vc_hkxxdz,
              '1',
              '外省') hjdz_text
  from zjjk_tnb_bgk a, zjjk_tnb_hzxx b, zjjk_tnb_bgk_zfgx c
 where a.vc_hzid = b.vc_personid
   and a.vc_gldw like #{vc_gldw} || '%'
   and a.vc_scbz = '0'
   and a.vc_bgkid = c.vc_fkid
   and exists(select 1
          from zjjk_tnb_bgk_zfgx gx
         where (gx.vc_fkid = #{vc_bgkid} or gx.vc_zkid = #{vc_bgkid})
           and (a.vc_bgkid = gx.vc_fkid or a.vc_bgkid = gx.vc_zkid))
   and rownum <= 200      
   order by decode(c.vc_fkid, c.vc_zkid, 0, 1)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         