SELECT id,
       jbxxybgksfyz,
       kpbm,
       kpbmxg,
       kpzt,
       kpztxg,
       hzxm,
       hzxmxg,
       xb,
       xbxg,
       sfzh,
       sfzhxg,
       dts(csrq,'0') csrq,
       csrqxg,
       lxdh,
       lxdhxg,
       zdyy,
       zdyyxg,
       zdmc,
       zdmcxg,
       dts(fbrq,'0') fbrq,
       fbrqxg,
       hjdz,
       hjdzxg,
       sfsw,
       sfswxg,
       dts(swrq,'0') swrq,
       swrqxg,
       gbsy,
       gbsyxg,
       fhfs,
       fhry,
       dts(jcsj,'0') jcsj,
       sffh,
       fhzt,
       cjrid,
       cjrxm,
       dts(cjsj,'0') cjsj,
       xgrid,
       xgrxm,
       dts(xgsj,'0') xgsj,
       kpbmsh,
       kpztsh,
       hzxmsh,
       xbsh,
       sfzhsh,
       csrqsh,
       lxdhsh,
       zdyysh,
       zdmcsh,
       fbrqsh,
       hjdzsh,
       sfswsh,
       swrqsh,
       gbsysh
  FROM zjjk_cf_zlfh_mxbjc
 WHERE id = #{id}