SELECT id,
       jbxxybgksfyz,
       kpbm,
       kpbmxg,
       szxm,
       szxmxg,
       xb,
       xbxg,
       sfzh,
       sfzhxg,
       lxjs,
       lxjsxg,
       lxdh,
       lxdhxg,
       hjdz,
       hjdzxg,
       dts(swrq, 0) swrq,
       swrqxg,
       gbsy,
       gbsyxg,
       fhfs,
       fhry,
       dts(jcsj, 0) jcsj,
       sffh,
       fhzt,
       cjrid,
       cjrxm,
       dts(cjsj, 0) cjsj,
       xgrid,
       xgrxm,
       dts(xgsj, 0) xgsj,
       kpbmsh,
       szxmsh,
       xbsh,
       sfzhsh,
       lxjssh,
       lxdhsh,
       hjdzsh,
       swrqsh,
       gbsysh
  FROM zjjk_cf_zlfh_swga
 WHERE id = #{id}