SELECT id,
       jbxxybgksfyz,
       kpbm,
       kpbmxg,
       hzxm,
       hzxmxg,
       lxdh,
       lxdhxg,
       hjdz,
       hjdzxg,
       sczt,
       scztxg,
       dts(swrq, '0') swrq,
       swrqxg,
       gbsy,
       gbsyxg,
       jynhjsfbh,
       fhfs,
       fhry,
       dts(jcsj, '0') jcsj,
       sffh,
       fhzt,
       kpbmsh,
       hzxmsh,
       lxdhsh,
       hjdzsh,
       scztsh,
       swrqsh,
       gbsysh
  FROM zjjk_sf_zlfh_mxbjc
 WHERE id = #{id}