SELECT id,
       bgkid,
       vc_bgkid,
       cctjid,
       vc_bgkcode vc_bgkbh,
       '肿瘤' vc_mblx,
       ccbz,
       decode(ccbz,
              '101',
              '脑卒中',
              '201',
              '冠心病',
              '301',
              '糖尿病',
              '401',
              '肺癌',
              '402',
              '肝癌',
              '403',
              '胃癌',
              '404',
              '食管癌',
              '405',
              '结、直肠癌',
              '406',
              '女性乳腺癌',
              '407',
              '其他恶性肿瘤') ccbz_text,
       vc_bgkzt,
       vc_hzxm vc_xm,
       decode(vc_hzxb, '1', '男', '2', '女') vc_hzxb_text,
       dts(dt_hzcsrq, 0) csrq,
       dts(dt_sczdrq, 0) qzrq,
       vc_zdyh zdyj,
       (SELECT icd10_code || '-' || icd10_name
          FROM t_icd10
         WHERE t_icd10.icd10_code = vc_icd10) zdmc,
       vc_sfzh,
       (SELECT mc FROM p_yljg WHERE dm = vc_bgdw) bkdw_text,
       ccczrid,
       fn_zjjk_zlfh_mb_getfhjg(#{vc_mblx},vc_bgkid,cctjid) fhjgpd,
       fhzt fhzt,
       decode(fhzt,
              '0',
              '未开始',
              '1',
              '进行中',
              '2',
              '待复核',
              '3',
              '复核通过',
              '4',
              '复核不通过',
              '5',
              '审核通过',
              '6',
              '审核不通过') fhzt_text,
       shyj,
       rn,
       total
  FROM (SELECT id,
               bgkid,
               vc_bgkid,
               cctjid,
               vc_bgkcode,
               ccbz,
               vc_bgkzt,
               vc_hzxm,
               vc_hzxb,
               dt_hzcsrq,
               dt_sczdrq,
               vc_zdyh,
               vc_icd10,
               vc_sfzh,
               vc_bgdw,
               ccczrid,
               fhzt,
               shyj,
               rownum     rn,
               total
          FROM (SELECT a.id,
                       a.bgkid,
                       b.vc_bgkid,
                       a.cctjid,
                       b.vc_bgkid vc_bgkcode,
                       a.ccbz,
                       b.vc_bgkzt,
                       c.vc_hzxm,
                       c.vc_hzxb,
                       c.dt_hzcsrq,
                       b.dt_sczdrq,
                       b.vc_zdyh,
                       b.vc_icd10,
                       c.vc_sfzh vc_sfzh,
                       b.vc_bgdw,
                       a.ccczrid,
                       a.fhzt,
                       a.shyj,
                       COUNT(1) over() total
                  FROM zjjk_mb_zlfh a, zjjk_zl_bgk b, zjjk_zl_hzxx c
                 WHERE a.bgkid = b.vc_bgkid
                   AND b.vc_hzid = c.vc_personid
                   AND (a.fhzt = '3' OR a.fhzt = '5' OR a.fhzt = '6')
                   AND a.zt = '1'
                   AND a.cctjid = #{ccsjd}
                   AND a.mblx = #{vc_mblx}
                   AND a.ccjgid LIKE #{vc_bkqx} || '%' 
                   <if if(StringUtils.isNotBlank(#{sfsh}))>
                     AND ( ('0' = #{sfsh} AND a.fhzt != '3') OR ('1' = #{sfsh} AND a.fhzt = '3'))
                   </if>
                    <if if(1==1)>
                 ORDER BY a.fhzt)
         WHERE rownum <= #{rn_e})
 WHERE rn >= #{rn_s}
                    </if>                                                                                                                                                                                                                                                                                                                                                                                                                                                                           