select vc_sfkid,
       vc_bgkid,
       vc_hzid,
       dts(dt_sfrq,0) dt_sfrq,
       nb_zgjg,
       nb_zgjg_qcdz,
       nb_zgjg_sfyy,
       dts(dt_swrq,0) dt_swrq,
       vc_swyy,
       vc_swdd,
       vc_scq,
       vc_zlxm,
       vc_ssyy,
       vc_hlyy,
       vc_flyy,
       vc_sfzy,
       dt_zysj,
       vc_czlqk,
       vc_mqqk,
       nb_kspf,
       vc_ysqm,
       vc_hzqm,
       vc_scbz,
       vc_cjyh,
       dt_cjsj,
       dt_xgsj,
       vc_xgyh,
       vc_sfcf,
       vc_sczzrq,
       dts(vc_scjzsj,0) vc_scjzsj,
       vc_scssyy,
       dts(vc_scssrq,0) vc_scssrq,
       vc_scssxz,
       vc_zyh,
       vc_blh,
       vc_qcd,
       vc_qcsdm,
       vc_qcqxdm,
       vc_qcjddm,
       vc_qcjw,
       vc_sfqc,
       dt_qcsj,
       vc_qcxxdz,
       vc_hjhs,
       vc_zybw,
       vc_zljzs,
       vc_gx,
       vc_lb,
       dts(vc_cxglrq,0) vc_cxglrq,
       vc_cxglyy,
       vc_jzdhs,
       vc_whsyy,
       vc_ssyy1,
       vc_ssyy2,
       vc_hlyy1,
       vc_hlyy2,
       vc_flyy1,
       vc_flyy2,
       vc_hjwhsyy,
       vc_swicd,
       vc_swicdmc,
       vc_xys,
       vc_rjxyzs,
       vc_scxyrqn,
       vc_scxyrqy,
       vc_mcxyrqn,
       vc_mcxyrqy,
       vc_hjxysjn,
       vc_hjxysjy,
       nb_tz,
       nb_sg,
       vc_gxbz,
       vc_id,
       vc_jzdhsyy,
       vc_sfhzl,
       vc_sfzh,
       upload_areaeport
  from zjjk_zl_ccsfk
 where vc_sfkid = #{vc_sfkid}
   and vc_bgkid = #{vc_bgkid}