select a.vc_gbsy         vc_icd10,
       a.vc_xm           vc_hzxm,
       a.vc_xb           vc_hzxb,
       a.vc_mz           vc_hzmz,
       a.vc_sfzhm        vc_sfzh,
   dts(a.dt_csrq,0)      dt_hzcsrq,
       a.vc_jslxdh       vc_jtdh,
       a.vc_hkqcs        vc_hksfdm,
       a.vc_hksdm        vc_hksdm,
       a.vc_hkqxdm       vc_hkqxdm,
       a.vc_hkjddm       vc_hkjddm,
       a.vc_hkjw         vc_hkjwdm,
       a.vc_hkxxdz       vc_hkxxdz,
       a.vc_hkqcs        vc_sjsfdm,
       a.vc_hksdm        vc_sjsdm,
       a.vc_hkqxdm       vc_sjqxdm,
       a.vc_hkjddm       vc_sjjddm,
       a.vc_hkjw         vc_sjjwdm,
       a.vc_hkxxdz       vc_sjxxdz,
       a.vc_zy           vc_hydm,
       a.vc_lxdzhgzdw    vc_gzdw,
       a.vc_gbsy         vc_icd10s,
       a.vc_sqzgzddw     vc_zgzddw,
   dts(a.dt_swrq,0)      dt_swrq,
       a.vc_gbsy         vc_swicd10,
       a.nb_gbsybm       vc_swicdmc,
       a.vc_sznl         vc_bksznl
  
  from zjmb_sw_bgk a
 where a.vc_bgkid = #{vc_bgkid}    