select a.vc_bgkid,
       a.vc_bgklx,
       a.vc_hzid,
       a.vc_icd10,
       a.vc_tnblx,
       a.vc_wxys,
       a.vc_wxystz,
       a.vc_wxyssg,
       a.vc_tnbs,
       a.vc_jzsrs,
       a.vc_ywbfz,
       a.vc_zslcbx,
       a.vc_zslcbxqt,
       a.nb_kfxtz,
       a.nb_sjxtz,
       a.nb_xjptt,
       a.nb_zdgc,
       a.nb_e4hdlc,
       a.nb_e5ldlc,
       a.nb_gysz,
       a.nb_nwldb,
       a.nbthxhdb,
       a.vc_bszyqt,
       dts(a.dt_sczdrq,0) as dt_sczdrq,
       a.vc_zddw,
       a.vc_bgdw,
       a.vc_bgys,
       dts(a.dt_bgrq,0) as dt_bgrq,
       a.vc_sfsw,
       dts(a.dt_swrq,0) as dt_swrq,
       a.vc_swyy,
       a.vc_swicd10,
       a.vc_swicdmc,
       a.vc_bszy,
       a.vc_scbz,
       a.vc_ccid,
       a.vc_ckbz,
       a.vc_sfbb,
       a.vc_sdqrzt,
       a.dt_qrsj,
       a.vc_sdqrid,
       dts(a.dt_cjsj,0) as dt_cjsj,
       a.vc_cjdw,
       dts(a.dt_xgsj,0) as dt_xgsj,
       a.vc_xgdw,
       a.vc_gldw,
       a.vc_shbz,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_SHZT',vc_shbz) vc_shbz_text,
       a.vc_shwtgyy1,
       a.vc_shwtgyy2,
       a.vc_khbz,
       a.vc_khjg,
       a.vc_smtjid,
       a.vc_qybz,
       a.vc_hkhs,
       a.vc_hkwhsyy,
       a.vc_jzhs,
       a.vc_jzwhsyy,
       a.vc_cxgl,
       a.vc_qcbz,
       a.vc_xgyh,
       a.vc_cjyh,
       a.vc_xxly,
       a.vc_bz,
       dts(a.dt_dcrq,0) as dt_dcrq,
       a.vc_dcr,
       a.vc_zdyh,
       a.vc_swxx,
       a.vc_bgdwqx,
       a.vc_zgzddw,
       a.vc_sznl,
       a.vc_icdo,
       a.vc_zyh,
       a.vc_mzh,
       a.vc_bqygzbr,
       a.vc_xzqybm,
       a.vc_bgkzt,
       a.vc_bgkcode,
       a.vc_qcd,
       a.vc_qcsdm,
       a.vc_qcqxdm,
       a.vc_qcjddm,
       a.vc_qcjw,
       a.vc_sfqc,
       dts(a.dt_qcsj,0) as dt_qcsj,
       a.vc_qcxxdz,
       a.vc_shid,
       a.vc_khid,
       a.vc_khzt,
       a.vc_shzt,
       a.vc_cfzt,
       a.vc_shwtgyy,
       a.vc_bks,
       a.vc_bkq,
       a.vc_bmi,
       a.vc_wtzt,
       a.vc_ywtdw,
       a.vc_sqsl,
       a.vc_jjsl,
       a.vc_ywtjd,
       a.vc_ywtjw,
       a.vc_ywtxxdz,
       a.vc_ywtjgdm,
       a.vc_lszy,
       a.vc_state,
       a.dt_yyshsj,
       a.dt_qxshsj,
       a.vc_bksznl,
       a.dt_cfsj,
       a.dt_sfsj,
       a.dt_qxzssj,
       a.vc_id,
       b.vc_hzxm,
       b.vc_hzxb,
       b.vc_hzmz,
       b.vc_whcd,
       dts(b.dt_hzcsrq,0) as dt_hzcsrq,
       b.vc_sfzh,
       b.vc_lxdh,
       b.vc_hydm,
       b.vc_zydm,
       b.vc_gzdw,
       b.vc_hkshen,
       b.vc_hks,
       b.vc_hkqx,
       b.vc_hkjd,
       b.vc_hkjw,
       b.vc_hkxxdz,
       b.vc_jzds,
       b.vc_jzs,
       b.vc_jzqx,
       b.vc_jzjd,
       b.vc_jzjw,
       b.vc_jzxxdz,
       c.vc_zkid,
       c.vc_fkid,
       d.mc vc_bgkdw_mc
  from zjjk_tnb_bgk a, zjjk_tnb_hzxx b, zjjk_tnb_bgk_zfgx c, p_yljg d
 where a.vc_hzid = b.vc_personid
   and a.vc_scbz = '0'
   and a.vc_bgkid = c.vc_fkid(+)
   and a.vc_bgkid = #{bgkid} 
   and a.vc_bgdw = d.dm(+)                                                                                                                                                              