select a.vc_bgkid,
       vc_bgklx,
       vc_hzid,
       vc_icd10,
       vc_tnblx,
       vc_wxys,
       vc_wxystz,
       vc_wxyssg,
       vc_tnbs,
       vc_jzsrs,
       vc_ywbfz,
       vc_zslcbx,
       vc_zslcbxqt,
       nb_kfxtz,
       nb_sjxtz,
       nb_xjptt,
       nb_zdgc,
       nb_e4hdlc,
       nb_e5ldlc,
       nb_gysz,
       nb_nwldb,
       nbthxhdb,
       vc_bszyqt,
       dts(dt_sczdrq, 0) dt_sczdrq,
       vc_zddw,
       vc_bgdw,
       vc_bgys,
       dt_bgrq,
       vc_sfsw,
       dts(dt_swrq, 0) dt_swrq,
       vc_swyy,
       vc_swicd10,
       vc_swicdmc,
       vc_bszy,
       vc_scbz,
       vc_ccid,
       vc_ckbz,
       vc_sfbb,
       vc_sdqrzt,
       dt_qrsj,
       vc_sdqrid,
       dts(dt_cjsj, 0) dt_cjsj,
       vc_cjdw,
       dt_xgsj,
       vc_xgdw,
       vc_gldw,
       vc_shbz,
       vc_shwtgyy1,
       vc_shwtgyy2,
       vc_khbz,
       vc_khjg,
       vc_smtjid,
       vc_qybz,
       vc_hkhs,
       vc_hkwhsyy,
       vc_jzhs,
       vc_jzwhsyy,
       vc_cxgl,
       vc_qcbz,
       vc_xgyh,
       vc_cjyh,
       vc_xxly,
       vc_bz,
       dt_dcrq,
       vc_dcr,
       vc_zdyh,
       vc_swxx,
       vc_bgdwqx,
       vc_zgzddw,
       a.vc_sznl,
       vc_icdo,
       vc_zyh,
       vc_mzh,
       vc_bqygzbr,
       vc_xzqybm,
       vc_bgkzt,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKZT',vc_bgkzt) vc_bgkzt_text,
       vc_bgkcode,
       vc_qcd,
       c.vc_qrcs,
       c.vc_qrqx,
       c.vc_qrjd,
       c.vc_qrjw,
       c.vc_qrxxdz,
       vc_shid,
       vc_khid,
       vc_khzt,
       vc_shzt,
       vc_cfzt,
       vc_shwtgyy,
       vc_bks,
       vc_bkq,
       vc_bmi,
       vc_wtzt,
       vc_ywtdw,
       vc_sqsl,
       vc_jjsl,
       vc_ywtjd,
       vc_ywtjw,
       vc_ywtxxdz,
       vc_ywtjgdm,
       vc_lszy,
       vc_state,
       dt_yyshsj,
       dts(dt_qxshsj, 0) dt_qxshsj,
       vc_bksznl,
       dt_cfsj,
       dt_sfsj,
       dt_qxzssj,
       c.vc_id vc_qyid,
       vc_hzxm,
       vc_hzxb,
       decode(vc_hzxb, '1', '男', '2', '女') vc_hzxb_text,
       vc_hzmz,
       vc_whcd,
       dts(dt_hzcsrq, 0) dt_hzcsrq,
       vc_sfzh,
       vc_lxdh,
       vc_hydm,
       vc_zydm,
       vc_gzdw,
       vc_hkshen,
       vc_hks,
       vc_hkqx,
       vc_hkjd,
       vc_hkjw,
       vc_hkxxdz,
       vc_jzds,
       vc_jzs,
       vc_jzqx,
       vc_jzjd,
       vc_jzjw,
       vc_jzxxdz,
       decode(vc_hkshen,'0','浙江省','1','外省') hkshen,
       pkg_zjmb_tnb.fun_getxzqhmc(vc_hks) hks,
       pkg_zjmb_tnb.fun_getxzqhmc(vc_hkqx) hkqx,
       pkg_zjmb_tnb.fun_getxzqhmc(vc_hkjd) hkjd,             
       decode(vc_hkshen,
              '0',
              '浙江省' ||
              pkg_zjmb_tnb.fun_getxzqhmc(vc_hks) ||
              pkg_zjmb_tnb.fun_getxzqhmc(vc_hkqx) ||
              pkg_zjmb_tnb.fun_getxzqhmc(vc_hkjd) ||
              vc_hkjw || vc_hkxxdz,
              '1',
              '外省') hjdz_text
                  from zjjk_tnb_bgk a, zjjk_tnb_hzxx b, zjjk_tnb_qrqcb c
                 where a.vc_hzid = b.vc_personid
                   and a.vc_bgkid = c.vc_bgkid
                   and c.vc_id = #{vc_qyid}
                                                             