select id,
       dm,
       mc,
       jc,
       pym,
       wbm,
       lb,
       gljgid,
       (select mc from p_yljg p where p.id = a.gljgid) gljgmc,
       xzqh,
       (select mc from p_xzdm x where x.dm = a.xzqh) xzqh_mc,
       jjlx,
       lxr,
       lxdh,
       szddz,
       szdxzqh,
       (select mc from p_xzdm x where x.dm = a.szdxzqh) szdxzqh_mc,
       xgsj,
       xgr,
       cjsj,
       cjr,
       bz,
       ptjgid,
       wtdm,
       zzjgdm
  from p_yljg a
 where id = #{jgid}