select xzmc,
       ksrq,
       jsrq,
       cjsj_ymd,
       jgdm,
       jgmc,
       hjsws,
       shjss,
       sfzhwzs,
       sybmbs,
       gbsybs,
       cfwcs,
       cfjss,
       shjsl,
       sfzhwzl,
       sybmbl,
       gbsybl,
       cfwcl,
       cfjsl,
       sort
  from (
select r.xzmc,
       dts(r.ksrq, 0) ksrq,
       dts(r.jsrq, 0) jsrq,
       dts(r.cjsj, 0) cjsj_ymd,
       t.jgdm,
       t.jgmc,
       t.hjsws,
       t.shjss,
       t.sfzhwzs,
       t.sybmbs,
       t.gbsybs,
       t.cfwcs,
       t.cfjss,
       trunc(t.shjss / decode(t.shjss, 0, 1, t.hjsws), 4) * 100 shjsl,
       trunc(t.sfzhwzs / decode(t.shjss, 0, 1, t.hjsws), 4) * 100 sfzhwzl,
       trunc(t.sybmbs / decode(t.shjss, 0, 1, t.hjsws), 4) * 100 sybmbl,
       trunc(t.gbsybs / decode(t.shjss, 0, 1, t.hjsws), 4) * 100 gbsybl,
       trunc(t.cfwcs / decode(t.shjss, 0, 1, t.hjsws), 4) * 100 cfwcl,
       trunc(t.cfjss / decode(t.shjss, 0, 1, t.hjsws), 4) * 100 cfjsl,
       0 sort
  from zjjk_tjbb_syzkb2 t, zjjk_tjbb_syzkb_report r
 where t.id = r.id
   and t.id = #{id}
union all
select '' xzmc,
       '' ksrq,
       '' jsrq,
       '' cjsj_ymd,
       '' jgdm,
       '合计' jgmc,
       sum(t.hjsws) hjsws,
       sum(t.shjss) shjss,
       sum(t.sfzhwzs) sfzhwzs,
       sum(t.sybmbs) sybmbs,
       sum(t.gbsybs) gbsybs,
       sum(t.cfwcs) cfwcs,
       sum(t.cfjss) cfjss,
       trunc(sum(t.shjss) / decode(sum(t.hjsws), 0, 1, sum(t.hjsws)), 4) * 100 shjsl,
       trunc(sum(t.sfzhwzs) / decode(sum(t.hjsws), 0, 1, sum(t.hjsws)), 4) * 100 sfzhwzl,
       trunc(sum(t.sybmbs) / decode(sum(t.hjsws), 0, 1, sum(t.hjsws)), 4) * 100 sybmbl,
       trunc(sum(t.gbsybs) / decode(sum(t.hjsws), 0, 1, sum(t.hjsws)), 4) * 100 gbsybl,
       trunc(sum(t.cfwcs) / decode(sum(t.hjsws), 0, 1, sum(t.hjsws)), 4) * 100 cfwcl,
       trunc(sum(t.cfjss) / decode(sum(t.hjsws), 0, 1, sum(t.hjsws)), 4) * 100 cfjsl,
       1 sort
  from zjjk_tjbb_syzkb2 t, zjjk_tjbb_syzkb_report r
 where t.id = r.id
   and t.id = #{id}
) order by sort, jgdm    