select bgk.vc_bgkid,
       bgk.vc_bgklx,
       bgk.vc_hzid,
       bgk.vc_shbz,
       bgk.vc_bgkzt,
       bgk.dt_bgrq,
       bgk.vc_icd10,
       bgk.vc_sfcf,
       bgk.dt_cjsj,
       bgk.DT_YYSHSJ,
       bgk.DT_QXSHSJ,
       bgk.DT_SFSJ,
       bgk.dt_cfsj,
       hzxx.vc_hzxm,
       hzxx.vc_hzxb,
       decode(hzxx.vc_hzxb, '1', '男', '2', '女') vc_hzxb_text,
       hzxx.vc_sfzh,
       hzxx.dt_hzcsrq,
       hzxx.VC_HKSFDM,
       hzxx.VC_HKSDM,
       hzxx.VC_HKQXDM,
       hzxx.VC_HKJDDM,
       hzxx.VC_HKJWDM vc_hkjw,
       hzxx.VC_HKXXDZ,
       pkg_zjmb_tnb.fun_getxzqhmc(hzxx.VC_HKSDM) hks,
       pkg_zjmb_tnb.fun_getxzqhmc(hzxx.VC_HKQXDM) hkqx,
       pkg_zjmb_tnb.fun_getxzqhmc(hzxx.VC_HKJDDM) hkjd,
       hzxx.vc_jtdh,
       c.VC_ID as qrqcid,
       c.VC_XTLB,
       c.vc_qccs,
       c.vc_qcqx,
       c.vc_qcjd,
       c.VC_QRCS,
       c.VC_QRQX,
       c.VC_QRJD,
       c.VC_QRDL,
       c.VC_QRJW,
       c.VC_QRXXDZ,
       c.DT_CLSJ,
       c.VC_CLFS,
       c.VC_QCR,
       c.VC_CLR,
       c.VC_ZHXGR,
       c.DT_ZHXGSJ,
       c.vc_id vc_qyid,
       count(1) over() as total
  from ZJJK_ZL_BGK bgk, ZJJK_ZL_HZXX hzxx, zjjk_zl_qrqcb c
 where bgk.vc_hzid = hzxx.vc_personid
   and c.vc_bgkid = bgk.vc_bgkid
   and c.vc_id = #{vc_qyid}  