select a.vc_bgkid,
        a.vc_mzh,
        a.vc_zyh,
        a.vc_bgkbh,
        a.vc_bgklx,
        a.vc_hzxm,
        a.vc_hzxb,
        a.vc_hzhy,
        a.vc_hzicd,
        dts(a.dt_hzcsrq,0) dt_hzcsrq,
        a.vc_sznl,
        a.vc_hzzy,
        a.vc_hzsfzh,
        a.vc_jtgz,
        a.vc_hzwhcd,
        a.vc_hzmz,
        a.vc_hzjtdh,
        a.vc_gzdw,
        a.vc_czhks,
        a.vc_czhksi,
        a.vc_czhkjd,
        a.vc_mqjzs,
        a.vc_mqjzsi,
        a.vc_mqjzjd,
        a.vc_mqjzjw,
        a.vc_gxbzd,
        a.vc_nczzd,
        a.vc_lczz,
        a.vc_xdt,
        a.vc_xqm,
        a.vc_njy,
        a.vc_ndt,
        a.vc_xgzy,
        a.vc_ct,
        a.vc_ckz,
        a.vc_sj,
        a.vc_sjkysjc,
        a.vc_bs,
        dts(a.dt_fbrq,0) dt_fbrq,
        dts(a.dt_qzrq,0) dt_qzrq,
        a.vc_sfsf,
        a.vc_qzdw,
        a.vc_bkdw,
        a.vc_bkys,
        dts(a.dt_bkrq,0) dt_bkrq,
        dts(a.dt_swrq,0) dt_swrq,
        a.vc_swys,
        a.vc_bszy,
        a.vc_scbz,
        a.vc_gldwdm,
        a.vc_cjdwdm,
        a.vc_ckbz,
        a.vc_sfbb,
        a.vc_sdqrzt,
        dts(a.dt_qrsj,0) dt_qrsj,
        a.vc_sdqrid,
        dts(a.dt_cjsj,0) dt_cjsj,
        a.vc_cjyh,
        dts(a.dt_xgsj,0) dt_xgsj,
        a.vc_xgyh,
        a.vc_shbz,
        a.vc_smtjid,
        a.vc_qcbz,
        a.vc_mqxxdz,
        a.vc_czhkjw,
        a.vc_czhkxxdz,
        a.vc_czhkqx,
        a.vc_mqjzqx,
        a.vc_swysicd,
        a.vc_swysmc,
        a.vc_bkdwqx,
        a.vc_bkdwyy,
        a.vc_sfcf,
        a.vc_kzt,
        a.vc_qcd,
        a.vc_qcsdm,
        a.vc_qcqxdm,
        a.vc_qcjddm,
        a.vc_qcjw,
        a.vc_sfqc,
        dts(a.dt_qcsj,0) dt_qcsj,
        a.vc_qcxxdz,
        a.vc_shid,
        a.vc_khzt,
        a.vc_khid,
        a.vc_khjg,
        a.vc_ccid,
        a.vc_khbz,
        a.vc_shzt,
        a.vc_sfsw,
        a.vc_shwtgyy,
        a.vc_shwtgyy1,
        a.vc_wtzt,
        a.vc_ywtdw,
        a.vc_sqsl,
        a.vc_jjsl,
        a.vc_ywtjd,
        a.vc_ywtjw,
        a.vc_ywtxxdz,
        a.vc_ywtjgdm,
        a.vc_lszy,
        a.vc_cgzsjjg,
        a.vc_syzz,
        a.vc_shtd,
        a.vc_state,
        dts(a.dt_yyshsj,0) dt_yyshsj,
        dts(a.dt_qxshsj,0) dt_qxshsj,
        a.vc_bksznl,
        dts(a.dt_cfsj,0) dt_cfsj,
        dts(a.dt_sfsj,0) dt_sfsj,
        a.vc_bak_hy,
        a.vc_bak_zy,
        a.vc_zssj,
        a.vc_gxbz,
        a.vc_id,
        a.vc_kz,
        a.vc_yyrid,
        a.dt_qxshrq,
        a.vc_nzzzyzz,
        a.vc_bak_sfzh,
        a.upload_areaeport,
        c.vc_zkid,
        c.vc_fkid,
        d.mc vc_bgkdw_mc
   from zjjk_xnxg_bgk a, zjjk_xnxg_bgk_zfgx c, p_yljg d
  where a.vc_bgkid = #{vc_bgkid}  
    and a.vc_bgkid = c.vc_fkid(+)
    and a.vc_bkdwyy = d.dm(+)