SELECT S.VC_SFKID,
       dts(S.DT_SFRQ, 0) dt_sfrq,
       S.VC_SFYS,
       S.VC_HJQC,
       S.VC_QYDZ,
       dts(S.DT_QYRQ, 0) dt_qyrq,
       S.VC_SFZLQK,
       S.VC_SFQFZQK,
       S.NB_SFQFZCS,
       dts(S.DT_DYCFBSJ, 0) dt_dycfbsj,
       dts(S.DT_DYCQZSJ, 0) dt_dycqzsj,
       dts(S.DT_DECFBSJ, 0) dt_decfbsj,
       dts(S.DT_DECQZSJ, 0) dt_decqzsj,
       dts(S.DT_DSCFBSJ, 0) dt_dscfbsj,
       dts(S.DT_DSCQZSJ, 0) dt_dscqzsj,
       S.VC_MQQK,
       S.VC_SFHYZ,
       dts(S.DT_CXGLRQ, 0) dt_cxglrq,
       S.VC_CXYY,
       S.VC_CXYYZM,
       S.NB_QZSJN,
       S.NB_QZSJY,
       dts(S.DT_SWRQ, 0) dt_swrq,
       S.VC_SWYY,
       S.VC_SWDD,
       S.NB_SCQN,
       S.NB_SCQY,
       S.VC_SCBZ,
       S.VC_CJYH,
       dts(S.DT_CJSJ, 0) dt_cjsj,
       dts(S.DT_XGSJ, 0) dt_xgsj,
       S.VC_XGYH,
       S.VC_QCD,
       S.VC_QCSDM,
       S.VC_QCQXDM,
       S.VC_QCJDDM,
       S.VC_QCJW,
       S.VC_QCXXDZ,
       S.VC_SWICD,
       S.VC_SWICDMC,
       S.VC_ZLQK,
       S.VC_JZS,
       S.VC_GX,
       S.VC_SFDYYJZ,
       dts(S.DT_QZRQ, 0) dt_qzrq,
       S.VC_XYS,
       S.VC_JYYF,
       S.VC_FZQRKPF,
       S.VC_CFRKPF,
       S.VC_YWZL,
       S.VC_YWZLQT,
       S.VC_ZLQK2,
       S.VC_ZLQK3,
       S.VC_SFFBSW1,
       S.VC_SFFBSW2,
       S.VC_SFFBSW3,
       S.VC_CFRKPF2,
       S.VC_CFRKPF3,
       S.VC_YWZL2,
       S.VC_YWZL3,
       S.VC_BFZ1,
       S.VC_BFZ2,
       S.VC_BFZ3,
       S.VC_GXBZ,
       S.VC_ID,
       S.UPLOAD_AREAEPORT,
       S.VC_YWZLQT3,
       S.VC_YWZLQT2,
       B.VC_BGKLX,
       B.VC_BGKBH,
       B.vc_MZH,
       B.vc_ZYH,
       b.vc_bgkid
  FROM ZJJK_XNXG_SFK S, ZJJK_XNXG_BGK B
 WHERE B.VC_BGKID = S.VC_BGKID(+) 
 <if if(StringUtils.isNotBlank(#{vc_bgkid}))>
      AND b.vc_bgkid = #{vc_bgkid}
 </if>
 <if if(StringUtils.isNotBlank(#{vc_sfkid}))>
      AND VC_SFKID = #{vc_sfkid}
 </if>