select vc_bgkid,
       vc_xm,
       vc_xb,
       vc_csrq,
       vc_fqxm,
       vc_mqxm,
       vc_qfrq,
       vc_mqnl,
       vc_fqnl,
       vc_csd,
       vc_yz,
       vc_jkzk,
       vc_sc,
       vc_tz,
       vc_fqgj,
       vc_fqmz,
       vc_mqgj,
       vc_mqmz,
       vc_fqsfz,
       vc_mqsfz,
       vc_jsjgmc,
       vc_jsr,
       vc_hjszd,
       vc_lxdh,
       vc_jtzz,
       vc_csddfl,
       vc_dryhmc,
       vc_dryhqxdm,
       vc_drsj,
       vc_drbz,
       vc_hjjd,
       vc_drsbyy
  from zjjk_csbgk_temp a
 where a.vc_bgkid = #{vc_bgkid}