select vc_sfkid,
         vc_bgkid,
         vc_hzid,
         dts(dt_sfrq,0) dt_sfrq,
         nb_zgjg,
         nb_zgjg_qcdz,
         nb_zgjg_sfyy,
         dts(dt_swrq,0) dt_swrq,
         vc_swyy,
         vc_swdd,
         vc_scq,
         vc_zlxm,
         vc_ssyy,
         vc_hlyy,
         vc_flyy,
         vc_sfzy,
         dts(dt_zysj,0) dt_zysj,
         vc_czlqk,
         vc_mqqk,
         nb_kspf,
         vc_ysqm,
         vc_hzqm,
         vc_scbz,
         vc_cjyh,
         dt_cjsj,
         dt_xgsj,
         vc_xgyh,
         dts(dt_sczdrq,0) dt_sczdrq,
         dts(dt_cxglrq,0) dt_cxglrq,
         vc_cxglyy,
         vc_sfcx,
         vc_cxglqtyy,
         vc_qcd,
         vc_qcsdm,
         vc_qcqxdm,
         vc_qcjddm,
         vc_qcjw,
         vc_sfqc,
         dts(dt_qcsj,0) dt_qcsj,
         vc_qcxxdz,
         vc_zybw,
         vc_ssyy1,
         vc_ssyy2,
         vc_hlyy1,
         vc_hlyy2,
         vc_flyy1,
         vc_flyy2,
         vc_sfff,
         vc_ffcs,
         dts(vc_ffsj,0) vc_ffsj,
         dts(vc_ffsj1,0) vc_ffsj1,
         dts(vc_ffsj2,0) vc_ffsj2,
         vc_swicd,
         vc_swicdmc,
         nb_tz,
         nb_sg,
         vc_bz,
         vc_sfxy,
         vc_gxbz,
         vc_id,
         upload_areaeport
    from zjjk_zl_sfk
   where vc_sfkid = #{vc_sfkid}
     and vc_bgkid = #{vc_bgkid}