SELECT sf.vc_sfkid,
       sf.vc_bgkid,
       sf.vc_hzid,
       sf.vc_bgkcode bgkbh,
       sf.vc_bgkzt,
       '4' vc_bllx,
       '肿瘤' bllx,
       #{vc_csflx} vc_csflx,
       decode(#{vc_csflx}, '1', '初访', '2', '随访') csflx,
       decode(#{vc_csflx}, '1', #{cfccsjd}, '2', #{sfccsjd}) vc_cctjid,
       hzxx.vc_hzxm xm,
       decode(hzxx.vc_hzxb, '1', '男', '2', '女') xb,
       hzxx.vc_sfzh sfzh,
       hzxx.vc_sjhm lxdh,
       decode(hzxx.vc_hksfdm,
              '0',
              '浙江省' || pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hksdm) ||
              pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hkqxdm) ||
              pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hkjddm) || hzxx.vc_hkjwdm ||
              hzxx.vc_hkxxdz,
              '1',
              '外省') hjdz,
       vc_gldw vc_bgdw,
       vc_zyh,
       (SELECT mc FROM p_yljg WHERE dm = sf.vc_gldw) bkdw,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKLX', sf.vc_bgklx) as vc_bgklx_text,
       sf.vc_mzh vc_mzh,
       sf.vc_icd10 vc_icd10,
       sf.vc_icd9 vc_icd9,
       sf.vc_bqygzbr,
       hzxx.vc_hzxb || ' ' || decode(hzxx.vc_hzxb, '1', '男', '2', '女') xb_text,
       dts(hzxx.dt_hzcsrq, 0) dt_hzcsrq,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKZT', sf.vc_bgkzt) as vc_bgkzt_text,
       hzxx.vc_zydm || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_HY', hzxx.vc_zydm) as vc_zydm_text,
       hzxx.vc_jtgz || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_ZY', hzxx.vc_jtgz) as vc_jtgz_text,
       sf.vc_bksznl vc_bksznl,
       hzxx.vc_hzmz || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_MZ', hzxx.vc_hzmz) as vc_hzmz_text,
       hzxx.vc_gzdw vc_gzdw,
       hzxx.vc_hksfdm || ' ' || decode(hzxx.vc_hksfdm, '0', '浙江省', '1', '外省') as vc_hksfdm_text,
       hzxx.vc_hksdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hksdm) as vc_hksdm_text,
       hzxx.vc_hkqxdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hkqxdm) as vc_hkqxdm_text,
       hzxx.vc_hkjddm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hkjddm) as vc_hkjddm_text,
       hzxx.vc_hkjwdm vc_hkjwdm,
       hzxx.vc_hkxxdz vc_hkxxdz,
       hzxx.vc_sjsfdm || ' ' || decode(hzxx.vc_sjsfdm, '0', '浙江省', '1', '外省') as vc_sjsfdm_text,
       hzxx.vc_sjsdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_sjsdm) as vc_sjsdm_text,
       hzxx.vc_sjqxdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hkqxdm) as vc_sjqxdm_text,
       hzxx.vc_sjjddm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hzxx.vc_hkjddm) as vc_sjjddm_text,
       hzxx.vc_sjjwdm vc_sjjwdm,
       hzxx.vc_sjxxdz vc_sjxxdz,
       sf.vc_zdbwmc vc_zdbwmc,
       sf.vc_icdo vc_icdo,
       sf.vc_icdM vc_icdM,
       sf.vc_dlw vc_dlw,
       sf.vc_blh vc_blh,
       sf.vc_zdqbt vc_zdqbt,
       sf.vc_zdqbN vc_zdqbN,
       sf.vc_zdqbM vc_zdqbM,
       sf.vc_zdsqb vc_zdsqb,
       sf.vc_zgzddw || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZGZDDW', sf.vc_zgzddw) as vc_zgzddw_text,
       dts(sf.dt_zdrq, 0) dt_zdrq,
       sf.vc_yzd vc_yzd,
       dts(sf.dt_yzdrq, 0) dt_yzdrq,
       sf.vc_bgdw || ' ' || (select d.mc from p_yljg d where d.dm(+) = sf.vc_bgdw) as vc_bgdw_text,
       sf.vc_bgys vc_bgys,
       dts(sf.dt_bgrq, 0) dt_bgrq,
       dts(sf.dt_swrq, 0) dt_swrq,
       sf.vc_swyy vc_swyy,
       sf.vc_swicd10 vc_swicd10,
       sf.vc_swicdmc vc_swicdmc,
       sf.vc_zdyh vc_zdyh,
       sf.vc_bszy vc_bszy,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_SHZT', sf.vc_shbz) as vc_shbz_text,
       dts(sf.bgk_dt_cjsj, 0) bgk_dt_cjsj,
       dts(sf.dt_yyshsj, 0) dt_yyshsj,
       dts(sf.dt_qxshsj, 0) dt_qxshsj,
       dts(sf.dt_cfsj, 0) dt_cfsj,
       dts(sf.dt_sfrq, 0) dt_sfrq,
       sf.vc_blxlx vc_blxlx,
       sf.vc_sfqc vc_sfqc,
       sf.vc_qcjddm vc_qcjddm,
       sf.vc_qcxxdz vc_qcxxdz,
       rn
  FROM (SELECT vc_sfkid,
               vc_bgkid,
               vc_hzid,
               vc_bgkcode,
               vc_bgkzt,
               vc_gldw,
               vc_zyh,
               vc_bgklx,
               vc_mzh,
               vc_icd10,
               vc_icd9,
               vc_bqygzbr,
               vc_bksznl,
               vc_zdbwmc,
               vc_icdo,
               vc_icdM,
               vc_dlw,
               vc_blh,
               vc_zdqbt,
               vc_zdqbN,
               vc_zdqbM,
               vc_zdsqb,
               vc_zgzddw,
               dt_zdrq,
               vc_yzd,
               dt_yzdrq,
               vc_bgdw,
               vc_bgys,
               dt_bgrq,
               dt_swrq,
               vc_swyy,
               vc_swicd10,
               vc_swicdmc,
               vc_zdyh,
               vc_bszy,
               vc_shbz,
               bgk_dt_cjsj,
               dt_yyshsj,
               dt_qxshsj,
               dt_cfsj,
               dt_sfrq,
               vc_blxlx,
               vc_sfqc,
               vc_qcjddm,
               vc_qcxxdz,
               rownum rn
          FROM (SELECT vc_sfkid,
                       vc_bgkid,
                       vc_hzid,
                       vc_bgkcode,
                       vc_bgkzt,
                       vc_gldw,
                       vc_zyh,
                       vc_bgklx,
                       vc_mzh,
                       vc_icd10,
                       vc_icd9,
                       vc_bqygzbr,
                       vc_bksznl,
                       vc_zdbwmc,
                       vc_icdo,
                       vc_icdM,
                       vc_dlw,
                       vc_blh,
                       vc_zdqbt,
                       vc_zdqbN,
                       vc_zdqbM,
                       vc_zdsqb,
                       vc_zgzddw,
                       dt_zdrq,
                       vc_yzd,
                       dt_yzdrq,
                       vc_bgdw,
                       vc_bgys,
                       dt_bgrq,
                       dt_swrq,
                       vc_swyy,
                       vc_swicd10,
                       vc_swicdmc,
                       vc_zdyh,
                       vc_bszy,
                       vc_shbz,
                       bgk_dt_cjsj,
                       dt_yyshsj,
                       dt_qxshsj,
                       dt_cfsj,
                       dt_sfrq,
                       vc_blxlx,
                       vc_sfqc,
                       vc_qcjddm,
                       vc_qcxxdz,
                       row_number() OVER(PARTITION BY vc_gldw ORDER BY nvl2(vc_zyh, 0, 1) asc, dbms_random.value) rowsnumber,
                       COUNT(1) over(PARTITION BY vc_gldw) countnumber
                  FROM (SELECT row_number() over(PARTITION BY sfk.vc_bgkid ORDER BY sfk.dt_cjsj) csfrn,
                               sfk.vc_sfkid,
                               sfk.vc_bgkid,
                               sfk.dt_cjsj,
                               bgk.vc_hzid,
                               bgk.vc_bgkid vc_bgkcode,
                               bgk.vc_bgkzt,
                               bgk.vc_gldw,
                               bgk.vc_zyh,
                               bgk.vc_icd10,
                               bgk.vc_bgklx,
                               bgk.vc_mzh,
                               bgk.vc_icd9,
                               bgk.vc_bqygzbr,
                               bgk.vc_bksznl,
                               bgk.vc_zdbwmc,
                               bgk.vc_icdo,
                               bgk.vc_icdM,
                               bgk.vc_dlw,
                               bgk.vc_blh,
                               bgk.vc_zdqbt,
                               bgk.vc_zdqbN,
                               bgk.vc_zdqbM,
                               bgk.vc_zdsqb,
                               bgk.vc_zgzddw,
                               bgk.dt_zdrq,
                               bgk.vc_yzd,
                               bgk.dt_yzdrq,
                               bgk.vc_bgdw,
                               bgk.vc_bgys,
                               bgk.dt_bgrq,
                               bgk.dt_swrq,
                               bgk.vc_swyy,
                               bgk.vc_swicd10,
                               bgk.vc_swicdmc,
                               bgk.vc_zdyh,
                               bgk.vc_bszy,
                               bgk.vc_shbz,
                               bgk.dt_cjsj bgk_dt_cjsj,
                               bgk.dt_yyshsj,
                               bgk.dt_qxshsj,
                               bgk.dt_cfsj,
                               bgk.dt_sfrq,
                               bgk.vc_blxlx,
                               bgk.vc_sfqc,
                               bgk.vc_qcjddm,
                               bgk.vc_qcxxdz
                          FROM zjjk_zl_sfk sfk, zjjk_zl_bgk bgk
                         WHERE sfk.vc_bgkid = bgk.vc_bgkid
                           AND bgk.vc_gldw LIKE #{vc_bgdw}||'%'
                           AND EXISTS (SELECT 1
                                 FROM p_yljgjb jg
                                WHERE bgk.vc_gldw = jg.jgdm
                                  AND jg.jbgjb IN ('乡级','村级')) 
                           AND bgk.vc_scbz = '0')
                 WHERE ((#{vc_csflx} = '1' AND csfrn = 1) OR
                       (#{vc_csflx} = '2' AND csfrn > 1))
                   AND ((#{vc_csflx} = '1' AND EXISTS
                        (SELECT 1
                            FROM zjjk_zlfhsj_cf cf
                           WHERE trunc(dt_cjsj) > trunc(cf.dt_ksrq)
                             AND trunc(dt_cjsj) <= trunc(cf.dt_jsrq)
                             AND cf.ccbz LIKE '%4%'
                             AND (cf.zlicd10 is null or cf.zlicd10||',' LIKE '%'||SUBSTR(vc_icd10,0,3)||',%')
                             AND (cf.bgkzt is null or vc_bgkzt in (select column_value from TABLE(split(cf.bgkzt, ','))))
                             AND cf.zt = '1')) OR
                       (#{vc_csflx} = '2' AND EXISTS
                        (SELECT 1
                            FROM zjjk_zlfhsj_sf sf
                           WHERE trunc(dt_cjsj) > trunc(sf.dt_ksrq)
                             AND trunc(dt_cjsj) <= trunc(sf.dt_jsrq)
                             AND sf.ccbz LIKE '%4%'
                             AND (sf.zlicd10 is null or sf.zlicd10||',' LIKE '%'||SUBSTR(vc_icd10,0,3)||',%')
                             AND (sf.bgkzt is null or vc_bgkzt in (select column_value from TABLE(split(sf.bgkzt, ','))))
                             AND sf.zt = '1')))
                   AND NOT EXISTS
                 (SELECT 1
                          FROM zjjk_csf_zlfh fh
                         WHERE fh.csflx = #{vc_csflx}
                           AND fh.bllx = '4'
                           AND fh.zt = '1'
                           AND fh.sfkid = vc_sfkid))
         WHERE rowsnumber <=
         <if if(StringUtils.isNotBlank(#{vc_csflx}) && "1".equals(#{vc_csflx}))>
             (SELECT tj.ccts FROM zjjk_zlfhsj_cf tj WHERE tj.zt = '1')
         </if>
         <if if(StringUtils.isNotBlank(#{vc_csflx}) && "2".equals(#{vc_csflx}))>
             (SELECT tj.ccts FROM zjjk_zlfhsj_sf tj WHERE tj.zt = '1')
         </if>
         ) sf,
       zjjk_zl_hzxx hzxx
 WHERE sf.vc_hzid = hzxx.vc_personid
   AND rn >= 0                                                                                                                                                                                                                                                                       