SELECT fh.id,
       fh.sfkid,
       bg.vc_bgkid,
       fh.cctjid,
       #{vc_csflx} vc_csflx,
       decode(#{vc_csflx},'1','初访','2','随访') csflx,
       bg.vc_bgkbh bgkbh,
       #{vc_bllx} vc_bllx,
       decode(#{vc_bllx},'1','脑卒中','2','冠心病') bllx,
       bg.vc_kzt vc_bgkzt,
       bg.vc_hzxm xm,
       DECODE(bg.vc_hzxb,'1','男','2','女') xb,
       bg.vc_hzsfzh sfzh,
       (select mc from P_YLJG where dm=bg.vc_gldwdm) bkdw,
       decode(bg.vc_czhks,
              '0',
              '浙江省' || pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_czhksi) ||
              pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_czhkqx) ||
              pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_czhkjd) || bg.vc_czhkjw ||
              bg.vc_czhkxxdz,
              '1',
              '外省') hjdz,
       bg.vc_hzjtdh lxdh,
       fh.fhbz fhbz,
       fn_zjjk_zlfh_csf_getfhjg(#{vc_csflx}, #{vc_bllx},fh.id) sffh,
       fh.fhzt vc_fhzt,
       fh.shyj,
       DECODE(fh.fhzt,'0','未开始','1','进行中','2','待复核','3','复核通过','4','复核不通过','5','审核通过','6','审核不通过') fhzt,
       bg.vc_zyh,
       lag(fh.fhzt, 1, null) over (order by fh.ccxh asc) last_fhzt,
       bg.vc_gldwdm vc_bgdw,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKLX', bg.vc_bgklx) as bgklx_text,
       bg.vc_mzh mzh,
       bg.vc_hzicd hzicd,
       bg.vc_hzxb || ' ' || decode(bg.vc_hzxb, '1', '男', '2', '女') xb_text,
       dts(bg.dt_hzcsrq, 0) hzcsrq,
       bg.vc_bksznl bksznl,
       bg.vc_hzzy || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_HY', bg.vc_hzzy) as hzzy_text,
       bg.vc_jtgz || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_ZY', bg.vc_jtgz) as jtgz_text,
       bg.vc_hzwhcd || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_WHCD', bg.vc_hzwhcd) as hzwhcd_text,
       bg.vc_hzmz || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_MZ', bg.vc_hzmz) as hzmz_text,
       bg.vc_czhks || ' ' || decode(bg.vc_czhks, '0', '浙江省', '1', '外省') as czhks_text,
       bg.vc_czhksi || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_czhksi) as czhksi_text,
       bg.vc_czhkqx || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_czhkqx) as czhkqx_text,
       bg.vc_czhkjd || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_czhkjd) as czhkjd_text,
       bg.vc_czhkjw czhkjw,
       bg.vc_czhkxxdz czhkxxdz,
       bg.vc_mqjzs || ' ' || decode(bg.vc_mqjzs, '0', '浙江省', '1', '外省') as mqjzs_text,
       bg.vc_mqjzsi || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_mqjzsi) as mqjzsi_text,
       bg.vc_mqjzqx || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_mqjzqx) as mqjzqx_text,
       bg.vc_mqjzjd || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(bg.vc_mqjzjd) as mqjzjd_text,
       bg.vc_mqjzjw mqjzjw,
       bg.vc_mqxxdz mqxxdz,
       bg.vc_gzdw vc_gzdw,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_GXBZD', bg.vc_gxbzd) as vc_gxbzd_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_NCZZD', bg.vc_nczzd) as vc_nczzd_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_lczz) as vc_lczz_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_xdt) as vc_xdt_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_xqm) as vc_xqm_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_njy) as vc_njy_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_ndt) as vc_ndt_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_xgzy) as vc_xgzy_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_ct) as vc_ct_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_ckz) as vc_ckz_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_sj) as vc_sj_text,
       pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZDYJ', bg.vc_sjkysjc) as vc_sjkysjc_text,
       bg.vc_bs vc_bs,
       bg.vc_bkdwyy || ' ' || (select d.mc from p_yljg d where d.dm = bg.vc_bkdwyy) as vc_bkdwyy_text,
       bg.vc_bkys vc_bkys,
       dts(bg.dt_bkrq, 0) dt_bkrq,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_SHZT', bg.vc_shbz) as vc_shbz_text,
       dts(bg.dt_yyshsj, 0) dt_yyshsj,
       dts(bg.dt_qxshsj, 0) dt_qxshsj,
       dts(bg.dt_fbrq, 0) dt_fbrq,
       dts(bg.dt_qzrq, 0) dt_qzrq,
       bg.vc_qzdw || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZGZDDW', bg.vc_qzdw) as vc_qzdw_text,
       bg.vc_sfsf vc_sfsf,
       bg.vc_swysicd vc_swysicd,
       bg.vc_swysmc vc_swysmc,
       dts(bg.dt_swrq, 0) dt_swrq,
       bg.vc_swys vc_swys,
       dts(bg.dt_cjsj, 0) bgk_dt_cjsj,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKZT', bg.vc_kzt) as vc_kzt_text,
       dts(bg.dt_cfsj, 0) dt_cfsj,
       dts(bg.dt_sfsj, 0) dt_sfsj,
       bg.vc_hzhy vc_hzhy,
       bg.vc_cgzsjjg || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_XNXG_CGZSJJG', bg.vc_cgzsjjg) as vc_cgzsjjg_text,
       bg.vc_syzz || '  ' || pkg_zjmb_tnb.fun_getcommdic('C_XNXG_SYZZ', bg.vc_syzz) as vc_syzz_text,
       bg.vc_bszy vc_bszy,
       bg.vc_sfqc vc_sfqc,
       bg.vc_qcjddm vc_qcjddm,
       bg.vc_qcxxdz vc_qcxxdz,
       COUNT(1) OVER() total
  FROM zjjk_csf_zlfh fh, zjjk_xnxg_bgk bg, zjjk_xnxg_sfk sf
 WHERE fh.sfkid = sf.vc_sfkid
   AND bg.vc_bgkid = sf.vc_bgkid
   AND fh.bllx = #{vc_bllx}
   AND fh.zt = '1'
   AND bg.vc_gldwdm LIKE #{vc_bgdw}||'%'
   AND (('1' = #{vc_csflx} AND cctjid=#{cfccsjd}) OR ('2' = #{vc_csflx} AND cctjid=#{sfccsjd}))  
   order by fh.ccxh asc                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                