SELECT fh.id,
       fh.sfkid,
       bg.vc_bgkid,
       fh.cctjid,
       #{vc_csflx} vc_csflx,
			 decode(#{vc_csflx},'1','初访','2','随访') csflx,
			 bg.vc_bgkid bgkbh,
       '4' vc_bllx,
       '肿瘤' bllx,
       bg.vc_bgkzt,
       hz.vc_hzxm xm,
       DECODE(hz.vc_hzxb,'1','男','2','女') xb,
       hz.vc_sfzh sfzh,
       (select mc from P_YLJG where dm=bg.vc_gldw) bkdw,
       decode(hz.vc_hksfdm ,
              '0',
              '浙江省' || pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hksdm ) ||
              pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hkqxdm ) ||
              pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hkjddm ) || hz.vc_hkjwdm  ||
              hz.vc_hkxxdz ,
              '1',
              '外省') hjdz,
       hz.vc_sjhm lxdh,
       fn_zjjk_zlfh_csf_getfhjg(#{vc_csflx}, #{vc_bllx},fh.id) sffh,
       fh.fhbz fhbz,
       fh.fhzt vc_fhzt,
       fh.shyj,
       DECODE(fh.fhzt,'0','未开始','1','进行中','2','待复核','3','复核通过','4','复核不通过','5','审核通过','6','审核不通过') fhzt,
       bg.vc_zyh,
       lag(fh.fhzt, 1, null) over (order by fh.ccxh asc) last_fhzt,
       bg.vc_gldw vc_bgdw,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKLX', bg.vc_bgklx) as vc_bgklx_text,
       bg.vc_mzh vc_mzh,
       bg.vc_icd10 vc_icd10,
       bg.vc_icd9 vc_icd9,
       bg.vc_bqygzbr,
       hz.vc_hzxb || ' ' || decode(hz.vc_hzxb, '1', '男', '2', '女') xb_text,
       dts(hz.dt_hzcsrq, 0) dt_hzcsrq,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_BGKZT', bg.vc_bgkzt) as vc_bgkzt_text,
       hz.vc_zydm || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_HY', hz.vc_zydm) as vc_zydm_text,
       hz.vc_jtgz || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_ZY', hz.vc_jtgz) as vc_jtgz_text,
       bg.vc_bksznl vc_bksznl,
       hz.vc_hzmz || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_COMM_MZ', hz.vc_hzmz) as vc_hzmz_text,
       hz.vc_gzdw vc_gzdw,
       hz.vc_hksfdm || ' ' || decode(hz.vc_hksfdm, '0', '浙江省', '1', '外省') as vc_hksfdm_text,
       hz.vc_hksdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hksdm) as vc_hksdm_text,
       hz.vc_hkqxdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hkqxdm) as vc_hkqxdm_text,
       hz.vc_hkjddm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hkjddm) as vc_hkjddm_text,
       hz.vc_hkjwdm vc_hkjwdm,
       hz.vc_hkxxdz vc_hkxxdz,
       hz.vc_sjsfdm || ' ' || decode(hz.vc_sjsfdm, '0', '浙江省', '1', '外省') as vc_sjsfdm_text,
       hz.vc_sjsdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_sjsdm) as vc_sjsdm_text,
       hz.vc_sjqxdm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hkqxdm) as vc_sjqxdm_text,
       hz.vc_sjjddm || ' ' || pkg_zjmb_tnb.fun_getxzqhmc(hz.vc_hkjddm) as vc_sjjddm_text,
       hz.vc_sjjwdm vc_sjjwdm,
       hz.vc_sjxxdz vc_sjxxdz,
       bg.vc_zdbwmc vc_zdbwmc,
       bg.vc_icdo vc_icdo,
       bg.vc_icdM vc_icdM,
       bg.vc_dlw vc_dlw,
       bg.vc_blh vc_blh,
       bg.vc_zdqbt vc_zdqbt,
       bg.vc_zdqbN vc_zdqbN,
       bg.vc_zdqbM vc_zdqbM,
       bg.vc_zdsqb vc_zdsqb,
       bg.vc_zgzddw || ' ' || pkg_zjmb_tnb.fun_getcommdic('C_XNXG_ZGZDDW', bg.vc_zgzddw) as vc_zgzddw_text,
       dts(bg.dt_zdrq, 0) dt_zdrq,
       bg.vc_yzd vc_yzd,
       dts(bg.dt_yzdrq, 0) dt_yzdrq,
       bg.vc_bgdw || ' ' || (select d.mc from p_yljg d where d.dm(+) = bg.vc_bgdw) as vc_bgdw_text,
       bg.vc_bgys vc_bgys,
       dts(bg.dt_bgrq, 0) dt_bgrq,
       dts(bg.dt_swrq, 0) dt_swrq,
       bg.vc_swyy vc_swyy,
       bg.vc_swicd10 vc_swicd10,
       bg.vc_swicdmc vc_swicdmc,
       bg.vc_zdyh vc_zdyh,
       bg.vc_bszy vc_bszy,
       pkg_zjmb_tnb.fun_getcommdic('C_COMM_SHZT', bg.vc_shbz) as vc_shbz_text,
       dts(bg.dt_cjsj, 0) bgk_dt_cjsj,
       dts(bg.dt_yyshsj, 0) dt_yyshsj,
       dts(bg.dt_qxshsj, 0) dt_qxshsj,
       dts(bg.dt_cfsj, 0) dt_cfsj,
       dts(bg.dt_sfrq, 0) dt_sfrq,
       bg.vc_blxlx vc_blxlx,
       bg.vc_sfqc vc_sfqc,
       bg.vc_qcjddm vc_qcjddm,
       bg.vc_qcxxdz vc_qcxxdz,
       COUNT(1) OVER() total
  FROM zjjk_csf_zlfh fh, zjjk_zl_sfk sf, zjjk_zl_bgk bg, zjjk_zl_hzxx hz
 WHERE fh.sfkid = sf.vc_sfkid
   AND sf.vc_bgkid = bg.vc_bgkid
   AND bg.vc_hzid = hz.vc_personid
   AND fh.bllx = '4'
   AND fh.zt = '1'
   AND fh.csflx = #{vc_csflx}
   AND bg.vc_gldw LIKE #{vc_bgdw}||'%'
   AND (('1' = #{vc_csflx} AND cctjid=#{cfccsjd}) OR ('2' = #{vc_csflx} AND cctjid=#{sfccsjd}))   
   order by fh.ccxh asc                                                                                                                                                                                                                                                                                                                                                                                                                                     