 select vc_bgkid,
        vc_mzh,
        vc_zyh,
        vc_bgkbh,
        vc_bgklx,
        vc_hzxm,
        vc_hzxb,
        decode(vc_hzxb, '1', '男', '2', '女') vc_hzxb_text,
        vc_hzhy,
        vc_hzicd,
        dts(dt_hzcsrq,0) dt_hzcsrq,
        vc_sznl,
        vc_hzzy,
        vc_hzsfzh,
        vc_jtgz,
        vc_hzwhcd,
        vc_hzmz,
        vc_hzjtdh,
        vc_gzdw,
        vc_czhks,
        vc_czhksi,
        vc_czhkjd,
        vc_mqjzs,
        vc_mqjzsi,
        vc_mqjzjd,
        vc_mqjzjw,
        vc_gxbzd,
        vc_nczzd,
        vc_lczz,
        vc_xdt,
        vc_xqm,
        vc_njy,
        vc_ndt,
        vc_xgzy,
        vc_ct,
        vc_ckz,
        vc_sj,
        vc_sjkysjc,
        vc_bs,
        dts(dt_fbrq,0) dt_fbrq,
        dts(dt_qzrq,0) dt_qzrq,
        vc_sfsf,
        vc_qzdw,
        vc_bkdw,
        vc_bkys,
        dts(dt_bkrq,0) dt_bkrq,
        dts(dt_swrq,0) dt_swrq,
        vc_swys,
        vc_bszy,
        vc_scbz,
        vc_gldwdm,
        vc_cjdwdm,
        vc_ckbz,
        vc_sfbb,
        vc_sdqrzt,
        dts(dt_qrsj,0) dt_qrsj,
        vc_sdqrid,
        dts(dt_cjsj,0) dt_cjsj,
        vc_cjyh,
        dts(dt_xgsj,0) dt_xgsj,
        vc_xgyh,
        vc_shbz,
        vc_smtjid,
        vc_qcbz,
        vc_mqxxdz,
        vc_czhkjw,
        vc_czhkxxdz,
        vc_czhkqx,
        pkg_zjmb_tnb.fun_getxzqhmc(vc_czhksi) vc_hksmc,
        pkg_zjmb_tnb.fun_getxzqhmc(vc_czhkqx) vc_hkqxmc,
        pkg_zjmb_tnb.fun_getxzqhmc(vc_czhkjd) vc_hkjdmc,
        vc_mqjzqx,
        vc_swysicd,
        vc_swysmc,
        vc_bkdwqx,
        vc_bkdwyy,
        vc_sfcf,
        vc_kzt,
        vc_qcd,
        vc_qcsdm,
        vc_qcqxdm,
        vc_qcjddm,
        vc_qcjw,
        vc_sfqc,
        dts(dt_qcsj,0) dt_qcsj,
        vc_qcxxdz,
        vc_shid,
        vc_khzt,
        vc_khid,
        vc_khjg,
        vc_ccid,
        vc_khbz,
        vc_shzt,
        vc_sfsw,
        vc_shwtgyy,
        vc_shwtgyy1,
        vc_wtzt,
        vc_ywtdw,
        vc_sqsl,
        vc_jjsl,
        vc_ywtjd,
        vc_ywtjw,
        vc_ywtxxdz,
        vc_ywtjgdm,
        vc_lszy,
        vc_cgzsjjg,
        vc_syzz,
        vc_shtd,
        vc_state,
        dts(dt_yyshsj,0) dt_yyshsj,
        dts(dt_qxshsj,0) dt_qxshsj,
        vc_bksznl,
        dts(dt_cfsj,0) dt_cfsj,
        dts(dt_sfsj,0) dt_sfsj,
        vc_bak_hy,
        vc_bak_zy,
        vc_zssj,
        vc_gxbz,
        vc_id,
        vc_kz,
        vc_yyrid,
        dt_qxshrq,
        vc_nzzzyzz,
        vc_bak_sfzh,
        upload_areaeport
   from zjjk_xnxg_bgk a
  where a.vc_bgkid = #{vc_bgkid}
   and a.vc_gldwdm like #{vc_gldw} || '%'
   and a.vc_scbz = '2'      