select bgk.vc_bgkid,
       bgk.vc_bgklx,
       bgk.vc_shbz,
       bgk.vc_bgkbh,
       bgk.vc_kzt vc_bgkzt,
       bgk.dt_bkrq dt_bgrq,
       bgk.VC_HZICD vc_icd10,
       bgk.vc_sfcf,
       bgk.dt_cjsj,
       bgk.DT_YYSHSJ,
       bgk.DT_QXSHSJ,
       bgk.DT_SFSJ,
       bgk.dt_cfsj,
       bgk.vc_hzxm,
       bgk.vc_hzxb,
       decode(bgk.vc_hzxb, '1', '男', '2', '女') vc_hzxb_text,
       bgk.VC_HZSFZH vc_sfzh,
       bgk.dt_hzcsrq,
       bgk.VC_CZHKS VC_HKSFDM,
       bgk.VC_CZHKS VC_HKSDM,
       bgk.VC_CZHKQX VC_HKQXDM,
       bgk.VC_CZHKJD VC_HKJDDM,
       bgk.VC_CZHKJW vc_hkjw,
       bgk.VC_CZHKXXDZ vc_hkxxdz,
       pkg_zjmb_tnb.fun_getxzqhmc(bgk.VC_CZHKSI) hks,
       pkg_zjmb_tnb.fun_getxzqhmc(bgk.VC_CZHKQX) hkqx,
       pkg_zjmb_tnb.fun_getxzqhmc(bgk.VC_CZHKJD) hkjd,
       bgk.VC_HZJTDH vc_jtdh,
       c.VC_ID as qrqcid,
       c.VC_XTLB,
       c.vc_qccs,
       c.vc_qcqx,
       c.vc_qcjd,
       c.VC_QRCS,
       c.VC_QRQX,
       c.VC_QRJD,
       c.VC_QRDL,
       c.VC_QRJW,
       c.VC_QRXXDZ,
       c.DT_CLSJ,
       c.VC_CLFS,
       c.VC_QCR,
       c.VC_CLR,
       c.VC_ZHXGR,
       c.DT_ZHXGSJ,
       c.vc_id vc_qyid,
       count(1) over() as total
  from ZJJK_XNXG_BGK bgk, zjjk_zl_qrqcb c
 where c.vc_bgkid = bgk.vc_bgkid
   and c.vc_id = #{vc_qyid}        